/**
 * C65
 * Copyright (C) 2019 David Jolly
 *
 * C65 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * C65 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef C65_TOOL_LAUNCHER_TYPE_H_
#define C65_TOOL_LAUNCHER_TYPE_H_

#include "../include/type/exception.h"

namespace c65 {

	namespace tool {

		#define C65_TOOL_LAUNCHER_HEADER "[C65::TOOL::LAUNCHER]"
#ifndef NDEBUG
		#define C65_TOOL_LAUNCHER_EXCEPTION_HEADER C65_TOOL_LAUNCHER_HEADER " "
#else
		#define C65_TOOL_LAUNCHER_EXCEPTION_HEADER
#endif // NDEBUG

		enum {
			C65_TOOL_LAUNCHER_EXCEPTION_ACTION_INVALID = 0,
			C65_TOOL_LAUNCHER_EXCEPTION_ARGUMENT_INVALID,
			C65_TOOL_LAUNCHER_EXCEPTION_ARGUMENT_MISMATCH,
			C65_TOOL_LAUNCHER_EXCEPTION_INTERNAL,
			C65_TOOL_LAUNCHER_EXCEPTION_REGISTER_INVALID,
		};

		#define C65_TOOL_LAUNCHER_EXCEPTION_MAX C65_TOOL_LAUNCHER_EXCEPTION_REGISTER_INVALID

		static const std::string C65_TOOL_LAUNCHER_EXCEPTION_STR[] = {
			C65_TOOL_LAUNCHER_EXCEPTION_HEADER "Invalid action", // C65_TOOL_LAUNCHER_EXCEPTION_ACTION_INVALID
			C65_TOOL_LAUNCHER_EXCEPTION_HEADER "Invalid argument", // C65_TOOL_LAUNCHER_EXCEPTION_ARGUMENT_INVALID
			C65_TOOL_LAUNCHER_EXCEPTION_HEADER "Mismatch argument", // C65_TOOL_LAUNCHER_EXCEPTION_ARGUMENT_MISMATCH
			C65_TOOL_LAUNCHER_EXCEPTION_HEADER "Internal exception", // C65_TOOL_LAUNCHER_EXCEPTION_INTERNAL
			C65_TOOL_LAUNCHER_EXCEPTION_HEADER "Invalid register", // C65_TOOL_LAUNCHER_EXCEPTION_REGISTER_INVALID
			};

		#define C65_TOOL_LAUNCHER_EXCEPTION_STRING(_TYPE_) \
			(((_TYPE_) > C65_TOOL_LAUNCHER_EXCEPTION_MAX) ? STRING_UNKNOWN : \
				STRING(C65_TOOL_LAUNCHER_EXCEPTION_STR[_TYPE_]))

		#define THROW_C65_TOOL_LAUNCHER_EXCEPTION(_EXCEPT_) \
			THROW_C65_TOOL_LAUNCHER_EXCEPTION_FORMAT(_EXCEPT_, "", "")
		#define THROW_C65_TOOL_LAUNCHER_EXCEPTION_FORMAT(_EXCEPT_, _FORMAT_, ...) \
			THROW_EXCEPTION(C65_TOOL_LAUNCHER_EXCEPTION_STRING(_EXCEPT_), _FORMAT_, __VA_ARGS__)

		static const size_t ACTION_ARGUMENT_LEN[] = {
			1, // C65_ACTION_READ_BYTE
			1, // C65_ACTION_READ_REGISTER
			0, // C65_ACTION_READ_STATUS
			1, // C65_ACTION_READ_WORD
			2, // C65_ACTION_WRITE_BYTE
			2, // C65_ACTION_WRITE_REGISTER
			1, // C65_ACTION_WRITE_STATUS
			2, // C65_ACTION_WRITE_WORD
			};

		#define ACTION_ARGUMENT_LENGTH(_TYPE_) \
			(((_TYPE_) > C65_ACTION_MAX) ? 0 : \
				ACTION_ARGUMENT_LEN[_TYPE_])

		static const std::string ACTION_ARGUMENT_STR[] = {
			"<address>", // C65_ACTION_READ_BYTE
			"<register>", // C65_ACTION_READ_REGISTER
			"", // C65_ACTION_READ_STATUS
			"<address>", // C65_ACTION_READ_WORD
			"<address> <value>", // C65_ACTION_WRITE_BYTE
			"<register> <value>", // C65_ACTION_WRITE_REGISTER
			"<value>", // C65_ACTION_WRITE_STATUS
			"<address> <value>", // C65_ACTION_WRITE_WORD
			};

		#define ACTION_ARGUMENT_STRING(_TYPE_) \
			(((_TYPE_) > C65_ACTION_MAX) ? STRING_UNKNOWN : \
				STRING(ACTION_ARGUMENT_STR[_TYPE_]))

		static const std::string ACTION_DESCRIPTION_STR[] = {
			"Read byte from memory", // C65_ACTION_READ_BYTE
			"Read register value", // C65_ACTION_READ_REGISTER
			"Read status value", // C65_ACTION_READ_STATUS
			"Read word from memory", // C65_ACTION_READ_WORD
			"Write byte to memory", // C65_ACTION_WRITE_BYTE
			"Write register value", // C65_ACTION_WRITE_REGISTER
			"Write status value", // C65_ACTION_WRITE_STATUS
			"Write word to memory", // C65_ACTION_WRITE_WORD
			};

		#define ACTION_DESCRIPTION_STRING(_TYPE_) \
			(((_TYPE_) > C65_ACTION_MAX) ? STRING_UNKNOWN : \
				STRING(ACTION_DESCRIPTION_STR[_TYPE_]))

		static const std::string ACTION_LONG_STR[] = {
			"read-byte", // C65_ACTION_READ_BYTE
			"read-register", // C65_ACTION_READ_REGISTER
			"read-status", // C65_ACTION_READ_STATUS
			"read-word", // C65_ACTION_READ_WORD
			"write-byte", // C65_ACTION_WRITE_BYTE
			"write-register", // C65_ACTION_WRITE_REGISTER
			"write-status", // C65_ACTION_WRITE_STATUS
			"write-word", // C65_ACTION_WRITE_WORD
			};

		#define ACTION_LONG_STRING(_TYPE_) \
			(((_TYPE_) > C65_ACTION_MAX) ? STRING_UNKNOWN : \
				STRING(ACTION_LONG_STR[_TYPE_]))

		static const std::string ACTION_SHORT_STR[] = {
			"rb", // C65_ACTION_READ_BYTE
			"rr", // C65_ACTION_READ_REGISTER
			"rs", // C65_ACTION_READ_STATUS
			"rw", // C65_ACTION_READ_WORD
			"wb", // C65_ACTION_WRITE_BYTE
			"wr", // C65_ACTION_WRITE_REGISTER
			"ws", // C65_ACTION_WRITE_STATUS
			"ww", // C65_ACTION_WRITE_WORD
			};

		#define ACTION_SHORT_STRING(_TYPE_) \
			(((_TYPE_) > C65_ACTION_MAX) ? STRING_UNKNOWN : \
				STRING(ACTION_SHORT_STR[_TYPE_]))

		static const std::map<std::string, int> ACTION_MAP = {
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_READ_BYTE), C65_ACTION_READ_BYTE), // C65_ACTION_READ_BYTE
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_READ_REGISTER), C65_ACTION_READ_REGISTER), // C65_ACTION_READ_REGISTER
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_READ_STATUS), C65_ACTION_READ_STATUS), // C65_ACTION_READ_STATUS
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_READ_WORD), C65_ACTION_READ_WORD), // C65_ACTION_READ_WORD
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_WRITE_BYTE), C65_ACTION_WRITE_BYTE), // C65_ACTION_WRITE_BYTE
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_WRITE_REGISTER), C65_ACTION_WRITE_REGISTER), // C65_ACTION_WRITE_REGISTER
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_WRITE_STATUS), C65_ACTION_WRITE_STATUS), // C65_ACTION_WRITE_STATUS
			std::make_pair(ACTION_LONG_STRING(C65_ACTION_WRITE_WORD), C65_ACTION_WRITE_WORD), // C65_ACTION_WRITE_WORD
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_READ_BYTE), C65_ACTION_READ_BYTE), // C65_ACTION_READ_BYTE
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_READ_REGISTER), C65_ACTION_READ_REGISTER), // C65_ACTION_READ_REGISTER
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_READ_STATUS), C65_ACTION_READ_STATUS), // C65_ACTION_READ_STATUS
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_READ_WORD), C65_ACTION_READ_WORD), // C65_ACTION_READ_WORD
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_WRITE_BYTE), C65_ACTION_WRITE_BYTE), // C65_ACTION_WRITE_BYTE
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_WRITE_REGISTER), C65_ACTION_WRITE_REGISTER), // C65_ACTION_WRITE_REGISTER
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_WRITE_STATUS), C65_ACTION_WRITE_STATUS), // C65_ACTION_WRITE_STATUS
			std::make_pair(ACTION_SHORT_STRING(C65_ACTION_WRITE_WORD), C65_ACTION_WRITE_WORD), // C65_ACTION_WRITE_WORD
			};

		#define ACTION_SUPPORTED(_ARGUMENT_) \
			(ACTION_MAP.find(_ARGUMENT_) != ACTION_MAP.end())
		#define ACTION_TYPE(_ARGUMENT_) \
			ACTION_MAP.find(_ARGUMENT_)->second

		enum {
			ACTION_CONTROL_EXIT = 0,
			ACTION_CONTROL_HELP,
			ACTION_CONTROL_VERSION,
		};

		#define ACTION_CONTROL_MAX ACTION_CONTROL_VERSION

		static const std::string ACTION_CONTROL_STR[] = {
			"exit", // ACTION_CONTROL_EXIT
			"help", // ACTION_CONTROL_HELP
			"version", // ACTION_CONTROL_VERSION
			};

		#define ACTION_CONTROL_STRING(_TYPE_) \
			(((_TYPE_) > ACTION_CONTROL_MAX) ? STRING_UNKNOWN : \
				STRING(ACTION_CONTROL_STR[_TYPE_]))

		static const std::map<std::string, int> ACTION_CONTROL_MAP = {
			std::make_pair(ACTION_CONTROL_STRING(ACTION_CONTROL_EXIT), ACTION_CONTROL_EXIT), // ACTION_CONTROL_EXIT
			std::make_pair(ACTION_CONTROL_STRING(ACTION_CONTROL_HELP), ACTION_CONTROL_HELP), // ACTION_CONTROL_HELP
			std::make_pair(ACTION_CONTROL_STRING(ACTION_CONTROL_VERSION), ACTION_CONTROL_VERSION), // ACTION_CONTROL_VERSION
			};

		#define ACTION_CONTROL_SUPPORTED(_ARGUMENT_) \
			(ACTION_CONTROL_MAP.find(_ARGUMENT_) != ACTION_CONTROL_MAP.end())
		#define ACTION_CONTROL_TYPE(_ARGUMENT_) \
			ACTION_CONTROL_MAP.find(_ARGUMENT_)->second

		static const std::string ACTION_REGISTER_STR[] = {
			"a", // C65_REGISTER_ACCUMULATOR
			"x", // C65_REGISTER_INDEX_X
			"y", // C65_REGISTER_INDEX_Y
			"pc", // C65_REGISTER_PROGRAM_COUNTER
			"sp", // C65_REGISTER_STACK_POINTER
			};

		#define ACTION_REGISTER_STRING(_TYPE_) \
			(((_TYPE_) > C65_REGISTER_MAX) ? STRING_UNKNOWN : \
				STRING(ACTION_REGISTER_STR[_TYPE_]))

		static const std::map<std::string, int> ACTION_REGISTER_MAP = {
			std::make_pair(ACTION_REGISTER_STRING(C65_REGISTER_ACCUMULATOR), C65_REGISTER_ACCUMULATOR), // C65_REGISTER_ACCUMULATOR
			std::make_pair(ACTION_REGISTER_STRING(C65_REGISTER_INDEX_X), C65_REGISTER_INDEX_X), // C65_REGISTER_INDEX_X
			std::make_pair(ACTION_REGISTER_STRING(C65_REGISTER_INDEX_Y), C65_REGISTER_INDEX_Y), // C65_REGISTER_INDEX_Y
			std::make_pair(ACTION_REGISTER_STRING(C65_REGISTER_PROGRAM_COUNTER), C65_REGISTER_PROGRAM_COUNTER), // C65_REGISTER_PROGRAM_COUNTER
			std::make_pair(ACTION_REGISTER_STRING(C65_REGISTER_STACK_POINTER), C65_REGISTER_STACK_POINTER), // C65_REGISTER_STACK_POINTER
			};

		#define ACTION_REGISTER_SUPPORTED(_ARGUMENT_) \
			(ACTION_REGISTER_MAP.find(_ARGUMENT_) != ACTION_REGISTER_MAP.end())
		#define ACTION_REGISTER_TYPE(_ARGUMENT_) \
			ACTION_REGISTER_MAP.find(_ARGUMENT_)->second

		enum {
			ARGUMENT_DEBUG = 0,
			ARGUMENT_HELP,
			ARGUMENT_QUIET,
			ARGUMENT_VERSION,
		};

		#define ARGUMENT_DELIMITER "-"

		#define ARGUMENT_MAX ARGUMENT_VERSION
		#define ARGUMENT_MIN 1

		static const std::string ARGUMENT_DESCRIPTION_STR[] = {
			"Enable debug mode", // ARGUMENT_DEBUG
			"Display help information", // ARGUMENT_HELP
			"Enable quiet mode", // ARGUMENT_QUIET
			"Display version information", // ARGUMENT_VERSION
			};

		#define ARGUMENT_DESCRIPTION_STRING(_TYPE_) \
			(((_TYPE_) > ARGUMENT_MAX) ? STRING_UNKNOWN : \
				STRING(ARGUMENT_DESCRIPTION_STR[_TYPE_]))

		static const std::string ARGUMENT_LONG_STR[] = {
			ARGUMENT_DELIMITER ARGUMENT_DELIMITER "debug", // ARGUMENT_DEBUG
			ARGUMENT_DELIMITER ARGUMENT_DELIMITER "help", // ARGUMENT_HELP
			ARGUMENT_DELIMITER ARGUMENT_DELIMITER "quiet", // ARGUMENT_QUIET
			ARGUMENT_DELIMITER ARGUMENT_DELIMITER "version", // ARGUMENT_VERSION
			};

		#define ARGUMENT_LONG_STRING(_TYPE_) \
			(((_TYPE_) > ARGUMENT_MAX) ? STRING_UNKNOWN : \
				STRING(ARGUMENT_LONG_STR[_TYPE_]))

		static const std::string ARGUMENT_SHORT_STR[] = {
			ARGUMENT_DELIMITER "d", // ARGUMENT_DEBUG
			ARGUMENT_DELIMITER "h", // ARGUMENT_HELP
			ARGUMENT_DELIMITER "q", // ARGUMENT_QUIET
			ARGUMENT_DELIMITER "v", // ARGUMENT_VERSION
			};

		#define ARGUMENT_SHORT_STRING(_TYPE_) \
			(((_TYPE_) > ARGUMENT_MAX) ? STRING_UNKNOWN : \
				STRING(ARGUMENT_SHORT_STR[_TYPE_]))

		static const std::map<std::string, int> ARGUMENT_MAP = {
			std::make_pair(ARGUMENT_LONG_STRING(ARGUMENT_DEBUG), ARGUMENT_DEBUG), // ARGUMENT_DEBUG
			std::make_pair(ARGUMENT_LONG_STRING(ARGUMENT_HELP), ARGUMENT_HELP), // ARGUMENT_HELP
			std::make_pair(ARGUMENT_LONG_STRING(ARGUMENT_QUIET), ARGUMENT_QUIET), // ARGUMENT_QUIET
			std::make_pair(ARGUMENT_LONG_STRING(ARGUMENT_VERSION), ARGUMENT_VERSION), // ARGUMENT_VERSION
			std::make_pair(ARGUMENT_SHORT_STRING(ARGUMENT_DEBUG), ARGUMENT_DEBUG), // ARGUMENT_DEBUG
			std::make_pair(ARGUMENT_SHORT_STRING(ARGUMENT_HELP), ARGUMENT_HELP), // ARGUMENT_HELP
			std::make_pair(ARGUMENT_SHORT_STRING(ARGUMENT_QUIET), ARGUMENT_QUIET), // ARGUMENT_QUIET
			std::make_pair(ARGUMENT_SHORT_STRING(ARGUMENT_VERSION), ARGUMENT_VERSION), // ARGUMENT_VERSION
			};

		#define ARGUMENT_SUPPORTED(_ARGUMENT_) \
			(ARGUMENT_MAP.find(_ARGUMENT_) != ARGUMENT_MAP.end())
		#define ARGUMENT_TYPE(_ARGUMENT_) \
			ARGUMENT_MAP.find(_ARGUMENT_)->second

		#define HISTORY_MAX 10

		#define PROMPT "\n% "

		#define USAGE "c65 [args]"
	}
}

#endif // C65_TOOL_LAUNCHER_TYPE_H_
