/**
 * C65
 * Copyright (C) 2019 David Jolly
 *
 * C65 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * C65 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef C65_COMMON_COMMAND_H_
#define C65_COMMON_COMMAND_H_

enum {
	COMMAND_ADC = 0,
	COMMAND_AND,
	COMMAND_ASL,
	COMMAND_BBR0,
	COMMAND_BBR1,
	COMMAND_BBR2,
	COMMAND_BBR3,
	COMMAND_BBR4,
	COMMAND_BBR5,
	COMMAND_BBR6,
	COMMAND_BBR7,
	COMMAND_BBS0,
	COMMAND_BBS1,
	COMMAND_BBS2,
	COMMAND_BBS3,
	COMMAND_BBS4,
	COMMAND_BBS5,
	COMMAND_BBS6,
	COMMAND_BBS7,
	COMMAND_BCC,
	COMMAND_BCS,
	COMMAND_BEQ,
	COMMAND_BIT,
	COMMAND_BMI,
	COMMAND_BNE,
	COMMAND_BPL,
	COMMAND_BRA,
	COMMAND_BRK,
	COMMAND_BVC,
	COMMAND_BVS,
	COMMAND_CLC,
	COMMAND_CLD,
	COMMAND_CLI,
	COMMAND_CLV,
	COMMAND_CMP,
	COMMAND_CPX,
	COMMAND_CPY,
	COMMAND_DEC,
	COMMAND_DEX,
	COMMAND_DEY,
	COMMAND_EOR,
	COMMAND_INC,
	COMMAND_INX,
	COMMAND_INY,
	COMMAND_JMP,
	COMMAND_JSR,
	COMMAND_LDA,
	COMMAND_LDX,
	COMMAND_LDY,
	COMMAND_LSR,
	COMMAND_NOP,
	COMMAND_ORA,
	COMMAND_PHA,
	COMMAND_PHP,
	COMMAND_PHX,
	COMMAND_PHY,
	COMMAND_PLA,
	COMMAND_PLP,
	COMMAND_PLX,
	COMMAND_PLY,
	COMMAND_RMB0,
	COMMAND_RMB1,
	COMMAND_RMB2,
	COMMAND_RMB3,
	COMMAND_RMB4,
	COMMAND_RMB5,
	COMMAND_RMB6,
	COMMAND_RMB7,
	COMMAND_ROL,
	COMMAND_ROR,
	COMMAND_RTI,
	COMMAND_RTS,
	COMMAND_SBC,
	COMMAND_SEC,
	COMMAND_SED,
	COMMAND_SEI,
	COMMAND_SMB0,
	COMMAND_SMB1,
	COMMAND_SMB2,
	COMMAND_SMB3,
	COMMAND_SMB4,
	COMMAND_SMB5,
	COMMAND_SMB6,
	COMMAND_SMB7,
	COMMAND_STA,
	COMMAND_STP,
	COMMAND_STX,
	COMMAND_STY,
	COMMAND_STZ,
	COMMAND_TAX,
	COMMAND_TAY,
	COMMAND_TRB,
	COMMAND_TSB,
	COMMAND_TSX,
	COMMAND_TXA,
	COMMAND_TXS,
	COMMAND_TYA,
	COMMAND_WAI,
};

#define COMMAND_MAX COMMAND_WAI

static const std::string COMMAND_STR[] = {
	"adc ", // COMMAND_ADC
	"and ", // COMMAND_AND
	"asl ", // COMMAND_ASL
	"bbr0", // COMMAND_BBR0
	"bbr1", // COMMAND_BBR1
	"bbr2", // COMMAND_BBR2
	"bbr3", // COMMAND_BBR3
	"bbr4", // COMMAND_BBR4
	"bbr5", // COMMAND_BBR5
	"bbr6", // COMMAND_BBR6
	"bbr7", // COMMAND_BBR7
	"bbs0", // COMMAND_BBS0
	"bbs1", // COMMAND_BBS1
	"bbs2", // COMMAND_BBS2
	"bbs3", // COMMAND_BBS3
	"bbs4", // COMMAND_BBS4
	"bbs5", // COMMAND_BBS5
	"bbs6", // COMMAND_BBS6
	"bbs7", // COMMAND_BBS7
	"bcc ", // COMMAND_BCC
	"bcs ", // COMMAND_BCS
	"beq ", // COMMAND_BEQ
	"bit ", // COMMAND_BIT
	"bmi ", // COMMAND_BMI
	"bne ", // COMMAND_BNE
	"bpl ", // COMMAND_BPL
	"bra ", // COMMAND_BRA
	"brk ", // COMMAND_BRK
	"bvc ", // COMMAND_BVC
	"bvs ", // COMMAND_BVS
	"clc ", // COMMAND_CLC
	"cld ", // COMMAND_CLD
	"cli ", // COMMAND_CLI
	"clv ", // COMMAND_CLV
	"cmp ", // COMMAND_CMP
	"cpx ", // COMMAND_CPX
	"cpy ", // COMMAND_CPY
	"dec ", // COMMAND_DEC
	"dex ", // COMMAND_DEX
	"dey ", // COMMAND_DEY
	"eor ", // COMMAND_EOR
	"inc ", // COMMAND_INC
	"inx ", // COMMAND_INX
	"iny ", // COMMAND_INY
	"jmp ", // COMMAND_JMP
	"jsr ", // COMMAND_JSR
	"lda ", // COMMAND_LDA
	"ldx ", // COMMAND_LDX
	"ldy ", // COMMAND_LDY
	"lsr ", // COMMAND_LSR
	"nop ", // COMMAND_NOP
	"ora ", // COMMAND_ORA
	"pha ", // COMMAND_PHA
	"php ", // COMMAND_PHP
	"phx ", // COMMAND_PHX
	"phy ", // COMMAND_PHY
	"pla ", // COMMAND_PLA
	"plp ", // COMMAND_PLP
	"plx ", // COMMAND_PLX
	"ply ", // COMMAND_PLY
	"rmb0", // COMMAND_RMB0
	"rmb1", // COMMAND_RMB1
	"rmb2", // COMMAND_RMB2
	"rmb3", // COMMAND_RMB3
	"rmb4", // COMMAND_RMB4
	"rmb5", // COMMAND_RMB5
	"rmb6", // COMMAND_RMB6
	"rmb7", // COMMAND_RMB7
	"rol ", // COMMAND_ROL
	"ror ", // COMMAND_ROR
	"rti ", // COMMAND_RTI
	"rts ", // COMMAND_RTS
	"sbc ", // COMMAND_SBC
	"sec ", // COMMAND_SEC
	"sed ", // COMMAND_SED
	"sei ", // COMMAND_SEI
	"smb0", // COMMAND_SMB0
	"smb1", // COMMAND_SMB1
	"smb2", // COMMAND_SMB2
	"smb3", // COMMAND_SMB3
	"smb4", // COMMAND_SMB4
	"smb5", // COMMAND_SMB5
	"smb6", // COMMAND_SMB6
	"smb7", // COMMAND_SMB7
	"sta ", // COMMAND_STA
	"stp ", // COMMAND_STP
	"stx ", // COMMAND_STX
	"sty ", // COMMAND_STY
	"stz ", // COMMAND_STZ
	"tax ", // COMMAND_TAX
	"tay ", // COMMAND_TAY
	"trb ", // COMMAND_TRB
	"tsb ", // COMMAND_TSB
	"tsx ", // COMMAND_TSX
	"txa ", // COMMAND_TXA
	"txs ", // COMMAND_TXS
	"tya ", // COMMAND_TYA
	"wai ", // COMMAND_WAI
	};

#define COMMAND_STRING(_TYPE_) \
	(((_TYPE_) > COMMAND_MAX) ? STRING_UNKNOWN : \
		STRING(COMMAND_STR[_TYPE_]))

#define COMMAND_CYCLE_INTERRUPT 7

enum {
	COMMAND_LENGTH_NONE = 0,
	COMMAND_LENGTH_BYTE,
	COMMAND_LENGTH_WORD,
};

enum {
	COMMAND_MODE_ABSOLUTE = 0,
	COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT,
	COMMAND_MODE_ABSOLUTE_INDEX_X,
	COMMAND_MODE_ABSOLUTE_INDEX_Y,
	COMMAND_MODE_ABSOLUTE_INDIRECT,
	COMMAND_MODE_ACCUMULATOR,
	COMMAND_MODE_IMMEDIATE,
	COMMAND_MODE_IMPLIED,
	COMMAND_MODE_RELATIVE,
	COMMAND_MODE_STACK,
	COMMAND_MODE_ZERO_PAGE,
	COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT,
	COMMAND_MODE_ZERO_PAGE_INDEX_X,
	COMMAND_MODE_ZERO_PAGE_INDEX_Y,
	COMMAND_MODE_ZERO_PAGE_INDIRECT,
	COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX,
};

#define COMMAND_MODE_MAX COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX

static const uint8_t COMMAND_MODE_CYC[] = {
	4, // COMMAND_MODE_ABSOLUTE
	6, // COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT
	4, // COMMAND_MODE_ABSOLUTE_INDEX_X
	4, // COMMAND_MODE_ABSOLUTE_INDEX_Y
	6, // COMMAND_MODE_ABSOLUTE_INDIRECT
	2, // COMMAND_MODE_ACCUMULATOR
	2, // COMMAND_MODE_IMMEDIATE
	2, // COMMAND_MODE_IMPLIED
	2, // COMMAND_MODE_RELATIVE
	3, // COMMAND_MODE_STACK
	3, // COMMAND_MODE_ZERO_PAGE
	6, // COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT
	4, // COMMAND_MODE_ZERO_PAGE_INDEX_X
	4, // COMMAND_MODE_ZERO_PAGE_INDEX_Y
	5, // COMMAND_MODE_ZERO_PAGE_INDIRECT
	5, // COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX
	};

#define COMMAND_MODE_CYCLE(_TYPE_) \
	(((_TYPE_) > COMMAND_MODE_MAX) ? COMMAND_MODE_CYC[COMMAND_MODE_IMPLIED] : \
		COMMAND_MODE_CYC[_TYPE_])

static const uint8_t COMMAND_MODE_LEN[] = {
	COMMAND_LENGTH_WORD, // COMMAND_MODE_ABSOLUTE
	COMMAND_LENGTH_WORD, // COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT
	COMMAND_LENGTH_WORD, // COMMAND_MODE_ABSOLUTE_INDEX_X
	COMMAND_LENGTH_WORD, // COMMAND_MODE_ABSOLUTE_INDEX_Y
	COMMAND_LENGTH_WORD, // COMMAND_MODE_ABSOLUTE_INDIRECT
	COMMAND_LENGTH_NONE, // COMMAND_MODE_ACCUMULATOR
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_IMMEDIATE
	COMMAND_LENGTH_NONE, // COMMAND_MODE_IMPLIED
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_RELATIVE
	COMMAND_LENGTH_NONE, // COMMAND_MODE_STACK
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_ZERO_PAGE
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_ZERO_PAGE_INDEX_X
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_ZERO_PAGE_INDEX_Y
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_ZERO_PAGE_INDIRECT
	COMMAND_LENGTH_BYTE, // COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX
	};

#define COMMAND_MODE_LENGTH(_TYPE_) \
	(((_TYPE_) > COMMAND_MODE_MAX) ? COMMAND_MODE_LEN[COMMAND_MODE_IMPLIED] : \
		COMMAND_MODE_LEN[_TYPE_])

static const std::string COMMAND_MODE_STR[] = {
	"a      ", // COMMAND_MODE_ABSOLUTE
	"(a, x) ", // COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT
	"a, x   ", // COMMAND_MODE_ABSOLUTE_INDEX_X
	"a, y   ", // COMMAND_MODE_ABSOLUTE_INDEX_Y
	"(a)    ", // COMMAND_MODE_ABSOLUTE_INDIRECT
	"A      ", // COMMAND_MODE_ACCUMULATOR
	"#      ", // COMMAND_MODE_IMMEDIATE
	"i      ", // COMMAND_MODE_IMPLIED
	"r      ", // COMMAND_MODE_RELATIVE
	"s      ", // COMMAND_MODE_STACK
	"zp     ", // COMMAND_MODE_ZERO_PAGE
	"(zp, x)", // COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT
	"zp, x  ", // COMMAND_MODE_ZERO_PAGE_INDEX_X
	"zp, y  ", // COMMAND_MODE_ZERO_PAGE_INDEX_Y
	"(zp)   ", // COMMAND_MODE_ZERO_PAGE_INDIRECT
	"(zp), y", // COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX
	};

#define COMMAND_MODE_STRING(_TYPE_) \
	(((_TYPE_) > COMMAND_MODE_MAX) ? STRING_UNKNOWN : \
		STRING(COMMAND_MODE_STR[_TYPE_]))

enum {
	// 0x00
	COMMAND_TYPE_BRK_STACK = 0,
	COMMAND_TYPE_ORA_ZERO_PAGE_INDEX_INDIRECT, // ora (zp, x)
	COMMAND_TYPE_ILLEGAL_02, // nop i
	COMMAND_TYPE_ILLEGAL_03, // nop i
	COMMAND_TYPE_TSB_ZERO_PAGE, // tsb zp
	COMMAND_TYPE_ORA_ZERO_PAGE, // ora zp
	COMMAND_TYPE_ASL_ZERO_PAGE, // asl zp
	COMMAND_TYPE_RMB0_ZERO_PAGE, // rmb0 zp

	// 0x08
	COMMAND_TYPE_PHP_STACK, // php s
	COMMAND_TYPE_ORA_IMMEDIATE, // ora #
	COMMAND_TYPE_ASL_ACCUMULATOR, // asl A
	COMMAND_TYPE_ILLEGAL_0B, // nop i
	COMMAND_TYPE_TSB_ABSOLUTE, // tsb a
	COMMAND_TYPE_ORA_ABSOLUTE, // ora a
	COMMAND_TYPE_ASL_ABSOLUTE, // asl a
	COMMAND_TYPE_BBR0_RELATIVE, // bbr0 r

	// 0x10
	COMMAND_TYPE_BPL_RELATIVE, // bpl r
	COMMAND_TYPE_ORA_ZERO_PAGE_INDIRECT_INDEX, // ora (zp), y
	COMMAND_TYPE_ORA_ZERO_PAGE_INDIRECT, // ora (zp)
	COMMAND_TYPE_ILLEGAL_13, // nop i
	COMMAND_TYPE_TRB_ZERO_PAGE, // trb zp
	COMMAND_TYPE_ORA_ZERO_PAGE_INDEX_X, // ora zp, x
	COMMAND_TYPE_ASL_ZERO_PAGE_INDEX_X, // asl zp, x
	COMMAND_TYPE_RMB1_ZERO_PAGE, // rmb1 zp

	// 0x18
	COMMAND_TYPE_CLC_IMPLIED, // clc i
	COMMAND_TYPE_ORA_ABSOLUTE_INDEX_Y, // ora a, y
	COMMAND_TYPE_INC_ACCUMULATOR, // inc A
	COMMAND_TYPE_ILLEGAL_1B, // nop i
	COMMAND_TYPE_TRB_ABSOLUTE, // trb a
	COMMAND_TYPE_ORA_ABSOLUTE_INDEX_X, // ora a, x
	COMMAND_TYPE_ASL_ABSOLUTE_INDEX_X, // asl a, x
	COMMAND_TYPE_BBR1_RELATIVE, // bbr1 r

	// 0x20
	COMMAND_TYPE_JSR_ABSOLUTE, // jsr a
	COMMAND_TYPE_AND_ZERO_PAGE_INDEX_INDIRECT, // and (zp, x)
	COMMAND_TYPE_ILLEGAL_22, // nop i
	COMMAND_TYPE_ILLEGAL_23, // nop i
	COMMAND_TYPE_BIT_ZERO_PAGE, // bit zp
	COMMAND_TYPE_AND_ZERO_PAGE, // and zp
	COMMAND_TYPE_ROL_ZERO_PAGE, // rol zp
	COMMAND_TYPE_RMB2_ZERO_PAGE, // rmb2 zp

	// 0x28
	COMMAND_TYPE_PLP_STACK, // plp s
	COMMAND_TYPE_AND_IMMEDIATE, // and #
	COMMAND_TYPE_ROL_ACCUMULATOR, // rol A
	COMMAND_TYPE_ILLEGAL_2B, // nop i
	COMMAND_TYPE_BIT_ABSOLUTE, // bit a
	COMMAND_TYPE_AND_ABSOLUTE, // and a
	COMMAND_TYPE_ROL_ABSOLUTE, // rol a
	COMMAND_TYPE_BBR2_RELATIVE, // bbr2 r

	// 0x30
	COMMAND_TYPE_BMI_RELATIVE, // bmi r
	COMMAND_TYPE_AND_ZERO_PAGE_INDIRECT_INDEX, // and (zp), y
	COMMAND_TYPE_AND_ZERO_PAGE_INDIRECT, // and (zp)
	COMMAND_TYPE_ILLEGAL_33, // nop i
	COMMAND_TYPE_BIT_ZERO_PAGE_INDEX_X, // bit zp, x
	COMMAND_TYPE_AND_ZERO_PAGE_INDEX_X, // and zp, x
	COMMAND_TYPE_ROL_ZERO_PAGE_INDEX_X, // rol zp, x
	COMMAND_TYPE_RMB3_ZERO_PAGE, // rmb3 zp

	// 0x38
	COMMAND_TYPE_SEC_IMPLIED, // sec i
	COMMAND_TYPE_AND_ABSOLUTE_INDEX_Y, // and a, y
	COMMAND_TYPE_DEC_ACCUMULATOR, // dec A
	COMMAND_TYPE_ILLEGAL_3B, // nop i
	COMMAND_TYPE_BIT_ABSOLUTE_INDEX_X, // bit a, x
	COMMAND_TYPE_AND_ABSOLUTE_INDEX_X, // and a, x
	COMMAND_TYPE_ROL_ABSOLUTE_INDEX_X, // rol a, x
	COMMAND_TYPE_BBR3_RELATIVE, // bbr3 r

	// 0x40
	COMMAND_TYPE_RTI_STACK, // rti s
	COMMAND_TYPE_EOR_ZERO_PAGE_INDEX_INDIRECT, // eor (zp, x)
	COMMAND_TYPE_ILLEGAL_42, // nop i
	COMMAND_TYPE_ILLEGAL_43, // nop i
	COMMAND_TYPE_ILLEGAL_44, // nop i
	COMMAND_TYPE_EOR_ZERO_PAGE, // eor zp
	COMMAND_TYPE_LSR_ZERO_PAGE, // lsr zp
	COMMAND_TYPE_RMB4_ZERO_PAGE, // rmb4 zp

	// 0x48
	COMMAND_TYPE_PHA_STACK, // pha s
	COMMAND_TYPE_EOR_IMMEDIATE, // eor #
	COMMAND_TYPE_LSR_ACCUMULATOR, // lsr A
	COMMAND_TYPE_ILLEGAL_4B, // nop i
	COMMAND_TYPE_JMP_ABSOLUTE, // jmp a
	COMMAND_TYPE_EOR_ABSOLUTE, // eor a
	COMMAND_TYPE_LSR_ABSOLUTE, // lsr a
	COMMAND_TYPE_BBR4_RELATIVE, // bbr4 r

	// 0x50
	COMMAND_TYPE_BVC_RELATIVE, // bvc r
	COMMAND_TYPE_EOR_ZERO_PAGE_INDIRECT_INDEX, // eor (zp), y
	COMMAND_TYPE_EOR_ZERO_PAGE_INDIRECT, // eor (zp)
	COMMAND_TYPE_ILLEGAL_53, // nop i
	COMMAND_TYPE_ILLEGAL_54, // nop i
	COMMAND_TYPE_EOR_ZERO_PAGE_INDEX_X, // eor zp, x
	COMMAND_TYPE_LSR_ZERO_PAGE_INDEX_X, // lsr zp, x
	COMMAND_TYPE_RMB5_ZERO_PAGE, // rmb5 zp

	// 0x58
	COMMAND_TYPE_CLI_IMPLIED, // cli i
	COMMAND_TYPE_EOR_ABSOLUTE_INDEX_Y, // eor a, y
	COMMAND_TYPE_PHY_STACK, // phy s
	COMMAND_TYPE_ILLEGAL_5B, // nop i
	COMMAND_TYPE_ILLEGAL_5C, // nop i
	COMMAND_TYPE_EOR_ABSOLUTE_INDEX_X, // eor a, x
	COMMAND_TYPE_LSR_ABSOLUTE_INDEX_X, // lsr a, x
	COMMAND_TYPE_BBR5_RELATIVE, // bbr5 r

	// 0x60
	COMMAND_TYPE_RTS_STACK, // rts s
	COMMAND_TYPE_ADC_ZERO_PAGE_INDEX_INDIRECT, // adc (zp, x)
	COMMAND_TYPE_ILLEGAL_62, // nop i
	COMMAND_TYPE_ILLEGAL_63, // nop i
	COMMAND_TYPE_STZ_ZERO_PAGE, // stz zp
	COMMAND_TYPE_ADC_ZERO_PAGE, // adc zp
	COMMAND_TYPE_ROR_ZERO_PAGE, // ror zp
	COMMAND_TYPE_RMB6_ZERO_PAGE, // rmb6 zp

	// 0x68
	COMMAND_TYPE_PLA_STACK, // pla s
	COMMAND_TYPE_ADC_IMMEDIATE, // adc #
	COMMAND_TYPE_ROR_ACCUMULATOR, // ror A
	COMMAND_TYPE_ILLEGAL_6B, // nop i
	COMMAND_TYPE_JMP_ABSOLUTE_INDIRECT, // jmp (a)
	COMMAND_TYPE_ADC_ABSOLUTE, // adc a
	COMMAND_TYPE_ROR_ABSOLUTE, // ror a
	COMMAND_TYPE_BBR6_RELATIVE, // bbr6 r

	// 0x70
	COMMAND_TYPE_BVS_RELATIVE, // bvs r
	COMMAND_TYPE_ADC_ZERO_PAGE_INDIRECT_INDEX, // adc (zp), y
	COMMAND_TYPE_ADC_ZERO_PAGE_INDIRECT, // adc (zp)
	COMMAND_TYPE_ILLEGAL_73, // nop i
	COMMAND_TYPE_STZ_ZERO_PAGE_INDEX_X, // stz zp, x
	COMMAND_TYPE_ADC_ZERO_PAGE_INDEX_X, // adc zp, x
	COMMAND_TYPE_ROR_ZERO_PAGE_INDEX_X, // ror zp, x
	COMMAND_TYPE_RMB7_ZERO_PAGE, // rmb7 zp

	// 0x78
	COMMAND_TYPE_SEI_IMPLIED, // sei i
	COMMAND_TYPE_ADC_ABSOLUTE_INDEX_Y, // adc a, y
	COMMAND_TYPE_PLY_STACK, // ply s
	COMMAND_TYPE_ILLEGAL_7B, // nop i
	COMMAND_TYPE_JMP_ABSOLUTE_INDEX_INDIRECT, // jmp (a, x)
	COMMAND_TYPE_ADC_ABSOLUTE_INDEX_X, // adc a, x
	COMMAND_TYPE_ROR_ABSOLUTE_INDEX_X, // ror a, x
	COMMAND_TYPE_BBR7_RELATIVE, // bbr7 r

	// 0x80
	COMMAND_TYPE_BRA_RELATIVE, // bra r
	COMMAND_TYPE_STA_ZERO_PAGE_INDEX_INDIRECT, // sta (zp, x)
	COMMAND_TYPE_ILLEGAL_82, // nop i
	COMMAND_TYPE_ILLEGAL_83, // nop i
	COMMAND_TYPE_STY_ZERO_PAGE, // sty zp
	COMMAND_TYPE_STA_ZERO_PAGE, // sta zp
	COMMAND_TYPE_STX_ZERO_PAGE, // stx zp
	COMMAND_TYPE_SMB0_ZERO_PAGE, // smb0 zp

	// 0x88
	COMMAND_TYPE_DEY_IMPLIED, // dey i
	COMMAND_TYPE_BIT_IMMEDIATE, // bit #
	COMMAND_TYPE_TXA_IMPLIED, // txa i
	COMMAND_TYPE_ILLEGAL_8B, // nop i
	COMMAND_TYPE_STY_ABSOLUTE, // sty a
	COMMAND_TYPE_STA_ABSOLUTE, // sta a
	COMMAND_TYPE_STX_ABSOLUTE, // stx a
	COMMAND_TYPE_BBS0_RELATIVE, // bbs0 r

	// 0x90
	COMMAND_TYPE_BCC_RELATIVE, // bcc r
	COMMAND_TYPE_STA_ZERO_PAGE_INDIRECT_INDEX, // sta (zp), y
	COMMAND_TYPE_STA_ZERO_PAGE_INDIRECT, // sta (zp)
	COMMAND_TYPE_ILLEGAL_93, // nop i
	COMMAND_TYPE_STY_ZERO_PAGE_INDEX_X, // sty zp, x
	COMMAND_TYPE_STA_ZERO_PAGE_INDEX_X, // sta zp, x
	COMMAND_TYPE_STX_ZERO_PAGE_INDEX_Y, // stx zp, y
	COMMAND_TYPE_SMB1_ZERO_PAGE, // smb1 zp

	// 0x98
	COMMAND_TYPE_TYA_IMPLIED, // tya i
	COMMAND_TYPE_STA_ABSOLUTE_INDEX_Y, // sta a, y
	COMMAND_TYPE_TXS_IMPLIED, // txs i
	COMMAND_TYPE_ILLEGAL_9B, // nop i
	COMMAND_TYPE_STZ_ABSOLUTE, // stz a
	COMMAND_TYPE_STA_ABSOLUTE_INDEX_X, // sta a, x
	COMMAND_TYPE_STZ_ABSOLUTE_INDEX_X, // stz a, x
	COMMAND_TYPE_BBS1_RELATIVE, // bbs1 r

	// 0xa0
	COMMAND_TYPE_LDY_IMMEDIATE, // ldy #
	COMMAND_TYPE_LDA_ZERO_PAGE_INDEX_INDIRECT, // lda (zp, x)
	COMMAND_TYPE_LDX_IMMEDIATE, // ldx #
	COMMAND_TYPE_ILLEGAL_A3, // nop i
	COMMAND_TYPE_LDY_ZERO_PAGE, // ldy zp
	COMMAND_TYPE_LDA_ZERO_PAGE, // lda zp
	COMMAND_TYPE_LDX_ZERO_PAGE, // ldx zp
	COMMAND_TYPE_SMB2_ZERO_PAGE, // smb2 zp

	// 0xa8
	COMMAND_TYPE_TAY_IMPLIED, // tay i
	COMMAND_TYPE_LDA_IMMEDIATE, // lda #
	COMMAND_TYPE_TAX_IMPLIED, // tax i
	COMMAND_TYPE_ILLEGAL_AB, // nop i
	COMMAND_TYPE_LDY_ACCUMULATOR, // ldy A
	COMMAND_TYPE_LDA_ABSOLUTE, // lda a
	COMMAND_TYPE_LDX_ABSOLUTE, // ldx a
	COMMAND_TYPE_BBS2_RELATIVE, // bbs2 r

	// 0xb0
	COMMAND_TYPE_BCS_RELATIVE, // bcs r
	COMMAND_TYPE_LDA_ZERO_PAGE_INDIRECT_INDEX, // lda (zp), y
	COMMAND_TYPE_LDA_ZERO_PAGE_INDIRECT, // lda (zp)
	COMMAND_TYPE_ILLEGAL_B3, // nop i
	COMMAND_TYPE_LDY_ZERO_PAGE_INDEX_X, // ldy zp, x
	COMMAND_TYPE_LDA_ZERO_PAGE_INDEX_X, // lda zp, x
	COMMAND_TYPE_LDX_ZERO_PAGE_INDEX_Y, // ldx zp, y
	COMMAND_TYPE_SMB3_ZERO_PAGE, // smb3 zp

	// 0xb8
	COMMAND_TYPE_CLV_IMPLIED, // clv i
	COMMAND_TYPE_LDA_ABSOLUTE_INDEX_Y, // lda a, y
	COMMAND_TYPE_TSX_IMPLIED, // tsx i
	COMMAND_TYPE_ILLEGAL_BB, // nop i
	COMMAND_TYPE_LDY_ABSOLUTE_INDEX_X, // ldy a, x
	COMMAND_TYPE_LDA_ABSOLUTE_INDEX_X, // lda a, x
	COMMAND_TYPE_LDX_ABSOLUTE_INDEX_Y, // ldx a, y
	COMMAND_TYPE_BBS3_RELATIVE, // bbs3 r

	// 0xc0
	COMMAND_TYPE_CPY_IMMEDIATE, // cpy #
	COMMAND_TYPE_CMP_ZERO_PAGE_INDEX_INDIRECT, // cmp (zp, x)
	COMMAND_TYPE_ILLEGAL_C2, // nop i
	COMMAND_TYPE_ILLEGAL_C3, // nop i
	COMMAND_TYPE_CPY_ZERO_PAGE, // cpy zp
	COMMAND_TYPE_CMP_ZERO_PAGE, // cmp zp
	COMMAND_TYPE_DEC_ZERO_PAGE, // dec zp
	COMMAND_TYPE_SMB4_ZERO_PAGE, // smb4 zp

	// 0xc8
	COMMAND_TYPE_INY_IMPLIED, // iny i
	COMMAND_TYPE_CMP_IMMEDIATE, // cmp #
	COMMAND_TYPE_DEX_IMPLIED, // dex i
	COMMAND_TYPE_WAI_IMPLIED, // wai i
	COMMAND_TYPE_CPY_ABSOLUTE, // cpy a
	COMMAND_TYPE_CMP_ABSOLUTE, // cmp a
	COMMAND_TYPE_DEC_ABSOLUTE, // dec a
	COMMAND_TYPE_BBS4_RELATIVE, // bbs4 r

	// 0xd0
	COMMAND_TYPE_BNE_RELATIVE, // bne r
	COMMAND_TYPE_CMP_ZERO_PAGE_INDIRECT_INDEX, // cmp (zp), y
	COMMAND_TYPE_CMP_ZERO_PAGE_INDIRECT, // cmp (zp)
	COMMAND_TYPE_ILLEGAL_D3, // nop i
	COMMAND_TYPE_ILLEGAL_D4, // nop i
	COMMAND_TYPE_CMP_ZERO_PAGE_INDEX_X, // cmp zp, x
	COMMAND_TYPE_DEC_ZERO_PAGE_INDEX_X, // dec zp, x
	COMMAND_TYPE_SMB5_ZERO_PAGE, // smb5 zp

	// 0xd8
	COMMAND_TYPE_CLD_IMPLIED, // cld i
	COMMAND_TYPE_CMP_ABSOLUTE_INDEX_Y, // cmp a, y
	COMMAND_TYPE_PHX_STACK, // phx s
	COMMAND_TYPE_STP_IMPLIED, // stp i
	COMMAND_TYPE_ILLEGAL_DC, // nop i
	COMMAND_TYPE_CMP_ABSOLUTE_INDEX_X, // cmp a, x
	COMMAND_TYPE_DEC_ABSOLUTE_INDEX_X, // dec a, x
	COMMAND_TYPE_BBS5_RELATIVE, // bbs5 r

	// 0xe0
	COMMAND_TYPE_CPX_IMMEDIATE, // cpx #
	COMMAND_TYPE_SBC_ZERO_PAGE_INDEX_INDIRECT, // sbc (zp, x)
	COMMAND_TYPE_ILLEGAL_E2, // nop i
	COMMAND_TYPE_ILLEGAL_E3, // nop i
	COMMAND_TYPE_CPX_ZERO_PAGE, // cpx zp
	COMMAND_TYPE_SBC_ZERO_PAGE, // sbc zp
	COMMAND_TYPE_INC_ZERO_PAGE, // inc zp
	COMMAND_TYPE_SMB6_ZERO_PAGE, // smb6 zp

	// 0xe8
	COMMAND_TYPE_INX_IMPLIED, // inx i
	COMMAND_TYPE_SBC_IMMEDIATE, // sbc #
	COMMAND_TYPE_NOP_IMPLIED, // nop i
	COMMAND_TYPE_ILLEGAL_EB, // nop i
	COMMAND_TYPE_CPX_ABSOLUTE, // cpx a
	COMMAND_TYPE_SBC_ABSOLUTE, // sbc a
	COMMAND_TYPE_INC_ABSOLUTE, // inc a
	COMMAND_TYPE_BBS6_RELATIVE, // bbs6 r

	// 0xf0
	COMMAND_TYPE_BEQ_RELATIVE, // beq r
	COMMAND_TYPE_SBC_ZERO_PAGE_INDIRECT_INDEX, // sbc (zp), y
	COMMAND_TYPE_SBC_ZERO_PAGE_INDIRECT, // sbc (zp)
	COMMAND_TYPE_ILLEGAL_F3, // nop i
	COMMAND_TYPE_ILLEGAL_F4, // nop i
	COMMAND_TYPE_SBC_ZERO_PAGE_INDEX_X, // sbc zp, x
	COMMAND_TYPE_INC_ZERO_PAGE_INDEX_X, // inc zp, x
	COMMAND_TYPE_SMB7_ZERO_PAGE, // smb7 zp

	// 0xf8
	COMMAND_TYPE_SED_IMPLIED, // sed i
	COMMAND_TYPE_SBC_ABSOLUTE_INDEX_Y, // sbc a, y
	COMMAND_TYPE_PLX_STACK, // plx s
	COMMAND_TYPE_ILLEGAL_FB, // nop i
	COMMAND_TYPE_ILLEGAL_FC, // nop i
	COMMAND_TYPE_SBC_ABSOLUTE_INDEX_X, // sbc a, x
	COMMAND_TYPE_INC_ABSOLUTE_INDEX_X, // inc a, x
	COMMAND_TYPE_BBS7_RELATIVE, // bbs7 r
};

typedef struct {
	int type;
	int mode;
	uint8_t length;
	uint8_t cycle;
} command_t;

static const command_t CMD[] = {

	// 0x00
	{ COMMAND_BRK, COMMAND_MODE_STACK, COMMAND_LENGTH_BYTE, COMMAND_CYCLE_INTERRUPT }, // brk s
	{ COMMAND_ORA, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // ora (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_TSB, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // tsb zp
	{ COMMAND_ORA, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // ora zp
	{ COMMAND_ASL, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // asl zp
	{ COMMAND_RMB0, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb0 zp

	// 0x08
	{ COMMAND_PHP, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // php s
	{ COMMAND_ORA, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // ora #
	{ COMMAND_ASL, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // asl A
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_TSB, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // tsb a
	{ COMMAND_ORA, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // ora a
	{ COMMAND_ASL, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // asl a
	{ COMMAND_BBR0, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr0 r

	// 0x10
	{ COMMAND_BPL, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bpl r
	{ COMMAND_ORA, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // ora (zp), y
	{ COMMAND_ORA, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // ora (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_TRB, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // trb zp
	{ COMMAND_ORA, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // ora zp, x
	{ COMMAND_ASL, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // asl zp, x
	{ COMMAND_RMB1, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb1 zp

	// 0x18
	{ COMMAND_CLC, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // clc i
	{ COMMAND_ORA, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // ora a, y
	{ COMMAND_INC, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // inc A
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_TRB, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // trb a
	{ COMMAND_ORA, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // ora a, x
	{ COMMAND_ASL, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // asl a, x
	{ COMMAND_BBR1, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr1 r

	// 0x20
	{ COMMAND_JSR, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // jsr a
	{ COMMAND_AND, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // and (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_BIT, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // bit zp
	{ COMMAND_AND, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // and zp
	{ COMMAND_ROL, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rol zp
	{ COMMAND_RMB2, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb2 zp

	// 0x28
	{ COMMAND_PLP, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // plp s
	{ COMMAND_AND, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // and #
	{ COMMAND_ROL, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // rol A
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_BIT, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // bit a
	{ COMMAND_AND, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // and a
	{ COMMAND_ROL, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // rol a
	{ COMMAND_BBR2, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr2 r

	// 0x30
	{ COMMAND_BMI, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bmi r
	{ COMMAND_AND, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // and (zp), y
	{ COMMAND_AND, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // and (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_BIT, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // bit zp, x
	{ COMMAND_AND, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // and zp, x
	{ COMMAND_ROL, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // rol zp, x
	{ COMMAND_RMB3, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb3 zp

	// 0x38
	{ COMMAND_SEC, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // sec i
	{ COMMAND_AND, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // and a, y
	{ COMMAND_DEC, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // dec A
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_BIT, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // bit a, x
	{ COMMAND_AND, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // and a, x
	{ COMMAND_ROL, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // rol a, x
	{ COMMAND_BBR3, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr3 r

	// 0x40
	{ COMMAND_RTI, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // rti s
	{ COMMAND_EOR, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // eor (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_EOR, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // eor zp
	{ COMMAND_LSR, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // lsr zp
	{ COMMAND_RMB4, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb4 zp

	// 0x48
	{ COMMAND_PHA, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // pha s
	{ COMMAND_EOR, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // eor #
	{ COMMAND_LSR, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // lsr A
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_JMP, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // jmp a
	{ COMMAND_EOR, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // eor a
	{ COMMAND_LSR, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // lsr a
	{ COMMAND_BBR4, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr4 r

	// 0x50
	{ COMMAND_BVC, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bvc r
	{ COMMAND_EOR, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // eor (zp), y
	{ COMMAND_EOR, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // eor (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_EOR, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // eor zp, x
	{ COMMAND_LSR, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // lsr zp, x
	{ COMMAND_RMB5, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb5 zp

	// 0x58
	{ COMMAND_CLI, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // cli i
	{ COMMAND_EOR, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // eor a, y
	{ COMMAND_PHY, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // phy s
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_EOR, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // eor a, x
	{ COMMAND_LSR, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // lsr a, x
	{ COMMAND_BBR5, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr5 r

	// 0x60
	{ COMMAND_RTS, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // rts s
	{ COMMAND_ADC, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // adc (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_STZ, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // stz zp
	{ COMMAND_ADC, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // adc zp
	{ COMMAND_ROR, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // ror zp
	{ COMMAND_RMB6, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb6 zp

	// 0x68
	{ COMMAND_PLA, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // pla s
	{ COMMAND_ADC, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // adc #
	{ COMMAND_ROR, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // ror A
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_JMP, COMMAND_MODE_ABSOLUTE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDIRECT) }, // jmp (a)
	{ COMMAND_ADC, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // adc a
	{ COMMAND_ROR, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // ror a
	{ COMMAND_BBR6, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr6 r

	// 0x70
	{ COMMAND_BVS, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bvs r
	{ COMMAND_ADC, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // adc (zp), y
	{ COMMAND_ADC, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // adc (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_STZ, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // stz zp, x
	{ COMMAND_ADC, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // adc zp, x
	{ COMMAND_ROR, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // ror zp, x
	{ COMMAND_RMB7, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // rmb7 zp

	// 0x78
	{ COMMAND_SEI, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // sei i
	{ COMMAND_ADC, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // adc a, y
	{ COMMAND_PLY, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // ply s
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_JMP, COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_INDIRECT) }, // jmp (a, x)
	{ COMMAND_ADC, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // adc a, x
	{ COMMAND_ROR, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // ror a, x
	{ COMMAND_BBR7, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbr7 r

	// 0x80
	{ COMMAND_BRA, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bra r
	{ COMMAND_STA, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // sta (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_STY, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // sty zp
	{ COMMAND_STA, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // sta zp
	{ COMMAND_STX, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // stx zp
	{ COMMAND_SMB0, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb0 zp

	// 0x88
	{ COMMAND_DEY, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // dey i
	{ COMMAND_BIT, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // bit #
	{ COMMAND_TXA, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // txa i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_STY, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // sty a
	{ COMMAND_STA, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // sta a
	{ COMMAND_STX, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // stx a
	{ COMMAND_BBS0, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs0 r

	// 0x90
	{ COMMAND_BCC, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bcc r
	{ COMMAND_STA, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // sta (zp), y
	{ COMMAND_STA, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // sta (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_STY, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // sty zp, x
	{ COMMAND_STA, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // sta zp, x
	{ COMMAND_STX, COMMAND_MODE_ZERO_PAGE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_Y) }, // stx zp, y
	{ COMMAND_SMB1, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb1 zp

	// 0x98
	{ COMMAND_TYA, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // tya i
	{ COMMAND_STA, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // sta a, y
	{ COMMAND_TXS, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // txs i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_STZ, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // stz a
	{ COMMAND_STA, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // sta a, x
	{ COMMAND_STZ, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // stz a, x
	{ COMMAND_BBS1, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs1 r

	// 0xa0
	{ COMMAND_LDY, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // ldy #
	{ COMMAND_LDA, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // lda (zp, x)
	{ COMMAND_LDX, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // ldx #
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_LDY, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // ldy zp
	{ COMMAND_LDA, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // lda zp
	{ COMMAND_LDX, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // ldx zp
	{ COMMAND_SMB2, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb2 zp

	// 0xa8
	{ COMMAND_TAY, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // tay i
	{ COMMAND_LDA, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // lda #
	{ COMMAND_TAX, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // tax i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_LDY, COMMAND_MODE_ACCUMULATOR, COMMAND_MODE_LENGTH(COMMAND_MODE_ACCUMULATOR), COMMAND_MODE_CYCLE(COMMAND_MODE_ACCUMULATOR) }, // ldy A
	{ COMMAND_LDA, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // lda a
	{ COMMAND_LDX, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // ldx a
	{ COMMAND_BBS2, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs2 r

	// 0xb0
	{ COMMAND_BCS, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bcs r
	{ COMMAND_LDA, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // lda (zp), y
	{ COMMAND_LDA, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // lda (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_LDY, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // ldy zp, x
	{ COMMAND_LDA, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // lda zp, x
	{ COMMAND_LDX, COMMAND_MODE_ZERO_PAGE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_Y) }, // ldx zp, y
	{ COMMAND_SMB3, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb3 zp

	// 0xb8
	{ COMMAND_CLV, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // clv i
	{ COMMAND_LDA, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // lda a, y
	{ COMMAND_TSX, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // tsx i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_LDY, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // ldy a, x
	{ COMMAND_LDA, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // lda a, x
	{ COMMAND_LDX, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // ldx a, y
	{ COMMAND_BBS3, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs3 r

	// 0xc0
	{ COMMAND_CPY, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // cpy #
	{ COMMAND_CMP, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // cmp (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_CPY, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // cpy zp
	{ COMMAND_CMP, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // cmp zp
	{ COMMAND_DEC, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // dec zp
	{ COMMAND_SMB4, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb4 zp

	// 0xc8
	{ COMMAND_INY, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // iny i
	{ COMMAND_CMP, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // cmp #
	{ COMMAND_DEX, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // dex i
	{ COMMAND_WAI, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // wai i
	{ COMMAND_CPY, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // cpy a
	{ COMMAND_CMP, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // cmp a
	{ COMMAND_DEC, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // dec a
	{ COMMAND_BBS4, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs4 r

	// 0xd0
	{ COMMAND_BNE, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bne r
	{ COMMAND_CMP, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // cmp (zp), y
	{ COMMAND_CMP, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // cmp (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_CMP, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // cmp zp, x
	{ COMMAND_DEC, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // dec zp, x
	{ COMMAND_SMB5, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb5 zp

	// 0xd8
	{ COMMAND_CLD, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // cld i
	{ COMMAND_CMP, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // cmp a, y
	{ COMMAND_PHX, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // phx s
	{ COMMAND_STP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // stp i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_CMP, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // cmp a, x
	{ COMMAND_DEC, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // dec a, x
	{ COMMAND_BBS5, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs5 r

	// 0xe0
	{ COMMAND_CPX, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // cpx #
	{ COMMAND_SBC, COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // sbc (zp, x)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_CPX, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // cpx zp
	{ COMMAND_SBC, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // sbc zp
	{ COMMAND_INC, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // inc zp
	{ COMMAND_SMB6, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb6 zp

	// 0xe8
	{ COMMAND_INX, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // inx i
	{ COMMAND_SBC, COMMAND_MODE_IMMEDIATE, COMMAND_MODE_LENGTH(COMMAND_MODE_IMMEDIATE), COMMAND_MODE_CYCLE(COMMAND_MODE_IMMEDIATE) }, // sbc #
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_CPX, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // cpx a
	{ COMMAND_SBC, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // sbc a
	{ COMMAND_INC, COMMAND_MODE_ABSOLUTE, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE) }, // inc a
	{ COMMAND_BBS6, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs6 r

	// 0xf0
	{ COMMAND_BEQ, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // beq r
	{ COMMAND_SBC, COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // sbc (zp), y
	{ COMMAND_SBC, COMMAND_MODE_ZERO_PAGE_INDIRECT, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDIRECT), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDIRECT) }, // sbc (zp)
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_SBC, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // sbc zp, x
	{ COMMAND_INC, COMMAND_MODE_ZERO_PAGE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE_INDEX_X) }, // inc zp, x
	{ COMMAND_SMB7, COMMAND_MODE_ZERO_PAGE, COMMAND_MODE_LENGTH(COMMAND_MODE_ZERO_PAGE), COMMAND_MODE_CYCLE(COMMAND_MODE_ZERO_PAGE) }, // smb7 zp

	// 0xf8
	{ COMMAND_SED, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // sed i
	{ COMMAND_SBC, COMMAND_MODE_ABSOLUTE_INDEX_Y, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_Y), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_Y) }, // sbc a, y
	{ COMMAND_PLX, COMMAND_MODE_STACK, COMMAND_MODE_LENGTH(COMMAND_MODE_STACK), COMMAND_MODE_CYCLE(COMMAND_MODE_STACK) }, // plx s
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_NOP, COMMAND_MODE_IMPLIED, COMMAND_MODE_LENGTH(COMMAND_MODE_IMPLIED), COMMAND_MODE_CYCLE(COMMAND_MODE_IMPLIED) }, // nop i
	{ COMMAND_SBC, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // sbc a, x
	{ COMMAND_INC, COMMAND_MODE_ABSOLUTE_INDEX_X, COMMAND_MODE_LENGTH(COMMAND_MODE_ABSOLUTE_INDEX_X), COMMAND_MODE_CYCLE(COMMAND_MODE_ABSOLUTE_INDEX_X) }, // inc a, x
	{ COMMAND_BBS7, COMMAND_MODE_RELATIVE, COMMAND_MODE_LENGTH(COMMAND_MODE_RELATIVE), COMMAND_MODE_CYCLE(COMMAND_MODE_RELATIVE) }, // bbs7 r
	};

#define COMMAND(_TYPE_) \
	(((_TYPE_) > UINT8_MAX) ? CMD[COMMAND_TYPE_NOP_IMPLIED] : \
		CMD[_TYPE_])

#endif // C65_COMMON_COMMAND_H_
