/**
 * C65
 * Copyright (C) 2019 David Jolly
 *
 * C65 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * C65 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef C65_COMMON_INSTRUCTION_H_
#define C65_COMMON_INSTRUCTION_H_

enum {
	INSTRUCTION_ADC = 0,
	INSTRUCTION_AND,
	INSTRUCTION_ASL,
	INSTRUCTION_BBR0,
	INSTRUCTION_BBR1,
	INSTRUCTION_BBR2,
	INSTRUCTION_BBR3,
	INSTRUCTION_BBR4,
	INSTRUCTION_BBR5,
	INSTRUCTION_BBR6,
	INSTRUCTION_BBR7,
	INSTRUCTION_BBS0,
	INSTRUCTION_BBS1,
	INSTRUCTION_BBS2,
	INSTRUCTION_BBS3,
	INSTRUCTION_BBS4,
	INSTRUCTION_BBS5,
	INSTRUCTION_BBS6,
	INSTRUCTION_BBS7,
	INSTRUCTION_BCC,
	INSTRUCTION_BCS,
	INSTRUCTION_BEQ,
	INSTRUCTION_BIT,
	INSTRUCTION_BMI,
	INSTRUCTION_BNE,
	INSTRUCTION_BPL,
	INSTRUCTION_BRA,
	INSTRUCTION_BRK,
	INSTRUCTION_BVC,
	INSTRUCTION_BVS,
	INSTRUCTION_CLC,
	INSTRUCTION_CLD,
	INSTRUCTION_CLI,
	INSTRUCTION_CLV,
	INSTRUCTION_CMP,
	INSTRUCTION_CPX,
	INSTRUCTION_CPY,
	INSTRUCTION_DEC,
	INSTRUCTION_DEX,
	INSTRUCTION_DEY,
	INSTRUCTION_EOR,
	INSTRUCTION_INC,
	INSTRUCTION_INX,
	INSTRUCTION_INY,
	INSTRUCTION_JMP,
	INSTRUCTION_JSR,
	INSTRUCTION_LDA,
	INSTRUCTION_LDX,
	INSTRUCTION_LDY,
	INSTRUCTION_LSR,
	INSTRUCTION_NOP,
	INSTRUCTION_ORA,
	INSTRUCTION_PHA,
	INSTRUCTION_PHP,
	INSTRUCTION_PHX,
	INSTRUCTION_PHY,
	INSTRUCTION_PLA,
	INSTRUCTION_PLP,
	INSTRUCTION_PLX,
	INSTRUCTION_PLY,
	INSTRUCTION_RMB0,
	INSTRUCTION_RMB1,
	INSTRUCTION_RMB2,
	INSTRUCTION_RMB3,
	INSTRUCTION_RMB4,
	INSTRUCTION_RMB5,
	INSTRUCTION_RMB6,
	INSTRUCTION_RMB7,
	INSTRUCTION_ROL,
	INSTRUCTION_ROR,
	INSTRUCTION_RTI,
	INSTRUCTION_RTS,
	INSTRUCTION_SBC,
	INSTRUCTION_SEC,
	INSTRUCTION_SED,
	INSTRUCTION_SEI,
	INSTRUCTION_SMB0,
	INSTRUCTION_SMB1,
	INSTRUCTION_SMB2,
	INSTRUCTION_SMB3,
	INSTRUCTION_SMB4,
	INSTRUCTION_SMB5,
	INSTRUCTION_SMB6,
	INSTRUCTION_SMB7,
	INSTRUCTION_STA,
	INSTRUCTION_STP,
	INSTRUCTION_STX,
	INSTRUCTION_STY,
	INSTRUCTION_STZ,
	INSTRUCTION_TAX,
	INSTRUCTION_TAY,
	INSTRUCTION_TRB,
	INSTRUCTION_TSB,
	INSTRUCTION_TSX,
	INSTRUCTION_TXA,
	INSTRUCTION_TXS,
	INSTRUCTION_TYA,
	INSTRUCTION_WAI,
};

#define INSTRUCTION_MAX INSTRUCTION_WAI

static const std::string INSTRUCTION_STR[] = {
	"adc ", // INSTRUCTION_ADC
	"and ", // INSTRUCTION_AND
	"asl ", // INSTRUCTION_ASL
	"bbr0", // INSTRUCTION_BBR0
	"bbr1", // INSTRUCTION_BBR1
	"bbr2", // INSTRUCTION_BBR2
	"bbr3", // INSTRUCTION_BBR3
	"bbr4", // INSTRUCTION_BBR4
	"bbr5", // INSTRUCTION_BBR5
	"bbr6", // INSTRUCTION_BBR6
	"bbr7", // INSTRUCTION_BBR7
	"bbs0", // INSTRUCTION_BBS0
	"bbs1", // INSTRUCTION_BBS1
	"bbs2", // INSTRUCTION_BBS2
	"bbs3", // INSTRUCTION_BBS3
	"bbs4", // INSTRUCTION_BBS4
	"bbs5", // INSTRUCTION_BBS5
	"bbs6", // INSTRUCTION_BBS6
	"bbs7", // INSTRUCTION_BBS7
	"bcc ", // INSTRUCTION_BCC
	"bcs ", // INSTRUCTION_BCS
	"beq ", // INSTRUCTION_BEQ
	"bit ", // INSTRUCTION_BIT
	"bmi ", // INSTRUCTION_BMI
	"bne ", // INSTRUCTION_BNE
	"bpl ", // INSTRUCTION_BPL
	"bra ", // INSTRUCTION_BRA
	"brk ", // INSTRUCTION_BRK
	"bvc ", // INSTRUCTION_BVC
	"bvs ", // INSTRUCTION_BVS
	"clc ", // INSTRUCTION_CLC
	"cld ", // INSTRUCTION_CLD
	"cli ", // INSTRUCTION_CLI
	"clv ", // INSTRUCTION_CLV
	"cmp ", // INSTRUCTION_CMP
	"cpx ", // INSTRUCTION_CPX
	"cpy ", // INSTRUCTION_CPY
	"dec ", // INSTRUCTION_DEC
	"dex ", // INSTRUCTION_DEX
	"dey ", // INSTRUCTION_DEY
	"eor ", // INSTRUCTION_EOR
	"inc ", // INSTRUCTION_INC
	"inx ", // INSTRUCTION_INX
	"iny ", // INSTRUCTION_INY
	"jmp ", // INSTRUCTION_JMP
	"jsr ", // INSTRUCTION_JSR
	"lda ", // INSTRUCTION_LDA
	"ldx ", // INSTRUCTION_LDX
	"ldy ", // INSTRUCTION_LDY
	"lsr ", // INSTRUCTION_LSR
	"nop ", // INSTRUCTION_NOP
	"ora ", // INSTRUCTION_ORA
	"pha ", // INSTRUCTION_PHA
	"php ", // INSTRUCTION_PHP
	"phx ", // INSTRUCTION_PHX
	"phy ", // INSTRUCTION_PHY
	"pla ", // INSTRUCTION_PLA
	"plp ", // INSTRUCTION_PLP
	"plx ", // INSTRUCTION_PLX
	"ply ", // INSTRUCTION_PLY
	"rmb0", // INSTRUCTION_RMB0
	"rmb1", // INSTRUCTION_RMB1
	"rmb2", // INSTRUCTION_RMB2
	"rmb3", // INSTRUCTION_RMB3
	"rmb4", // INSTRUCTION_RMB4
	"rmb5", // INSTRUCTION_RMB5
	"rmb6", // INSTRUCTION_RMB6
	"rmb7", // INSTRUCTION_RMB7
	"rol ", // INSTRUCTION_ROL
	"ror ", // INSTRUCTION_ROR
	"rti ", // INSTRUCTION_RTI
	"rts ", // INSTRUCTION_RTS
	"sbc ", // INSTRUCTION_SBC
	"sec ", // INSTRUCTION_SEC
	"sed ", // INSTRUCTION_SED
	"sei ", // INSTRUCTION_SEI
	"smb0", // INSTRUCTION_SMB0
	"smb1", // INSTRUCTION_SMB1
	"smb2", // INSTRUCTION_SMB2
	"smb3", // INSTRUCTION_SMB3
	"smb4", // INSTRUCTION_SMB4
	"smb5", // INSTRUCTION_SMB5
	"smb6", // INSTRUCTION_SMB6
	"smb7", // INSTRUCTION_SMB7
	"sta ", // INSTRUCTION_STA
	"stp ", // INSTRUCTION_STP
	"stx ", // INSTRUCTION_STX
	"sty ", // INSTRUCTION_STY
	"stz ", // INSTRUCTION_STZ
	"tax ", // INSTRUCTION_TAX
	"tay ", // INSTRUCTION_TAY
	"trb ", // INSTRUCTION_TRB
	"tsb ", // INSTRUCTION_TSB
	"tsx ", // INSTRUCTION_TSX
	"txa ", // INSTRUCTION_TXA
	"txs ", // INSTRUCTION_TXS
	"tya ", // INSTRUCTION_TYA
	"wai ", // INSTRUCTION_WAI
	};

#define INSTRUCTION_STRING(_TYPE_) \
	(((_TYPE_) > INSTRUCTION_MAX) ? STRING_UNKNOWN : \
		STRING(INSTRUCTION_STR[_TYPE_]))

enum {
	INSTRUCTION_LENGTH_NONE = 0,
	INSTRUCTION_LENGTH_BYTE,
	INSTRUCTION_LENGTH_WORD,
};

enum {
	INSTRUCTION_MODE_ABSOLUTE = 0,
	INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT,
	INSTRUCTION_MODE_ABSOLUTE_INDEX_X,
	INSTRUCTION_MODE_ABSOLUTE_INDEX_Y,
	INSTRUCTION_MODE_ABSOLUTE_INDIRECT,
	INSTRUCTION_MODE_ACCUMULATOR,
	INSTRUCTION_MODE_IMMEDIATE,
	INSTRUCTION_MODE_IMPLIED,
	INSTRUCTION_MODE_INTERRUPT,
	INSTRUCTION_MODE_RELATIVE,
	INSTRUCTION_MODE_RETURN,
	INSTRUCTION_MODE_STACK,
	INSTRUCTION_MODE_ZERO_PAGE,
	INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT,
	INSTRUCTION_MODE_ZERO_PAGE_INDEX_X,
	INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y,
	INSTRUCTION_MODE_ZERO_PAGE_INDIRECT,
	INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX,
	INSTRUCTION_MODE_ZERO_PAGE_RELATIVE,
	// ---
	INSTRUCTION_MODE_ILLEGAL_NOP_0,
	INSTRUCTION_MODE_ILLEGAL_NOP_1,
	INSTRUCTION_MODE_ILLEGAL_NOP_2,
	INSTRUCTION_MODE_ILLEGAL_NOP_3,
	INSTRUCTION_MODE_ILLEGAL_NOP_4,
	INSTRUCTION_MODE_ILLEGAL_NOP_5,
};

#define INSTRUCTION_MODE_MAX INSTRUCTION_MODE_ILLEGAL_NOP_5

static const uint8_t INSTRUCTION_MODE_CYC[] = {
	4, // INSTRUCTION_MODE_ABSOLUTE
	6, // INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT
	4, // INSTRUCTION_MODE_ABSOLUTE_INDEX_X
	4, // INSTRUCTION_MODE_ABSOLUTE_INDEX_Y
	6, // INSTRUCTION_MODE_ABSOLUTE_INDIRECT
	2, // INSTRUCTION_MODE_ACCUMULATOR
	2, // INSTRUCTION_MODE_IMMEDIATE
	2, // INSTRUCTION_MODE_IMPLIED
	7, // INSTRUCTION_MODE_INTERRUPT
	2, // INSTRUCTION_MODE_RELATIVE
	6, // INSTRUCTION_MODE_RETURN
	3, // INSTRUCTION_MODE_STACK
	3, // INSTRUCTION_MODE_ZERO_PAGE
	6, // INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT
	4, // INSTRUCTION_MODE_ZERO_PAGE_INDEX_X
	4, // INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y
	5, // INSTRUCTION_MODE_ZERO_PAGE_INDIRECT
	5, // INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX
	5, // INSTRUCTION_MODE_ZERO_PAGE_RELATIVE
	// ---
	2, // INSTRUCTION_MODE_ILLEGAL_NOP_0
	1, // INSTRUCTION_MODE_ILLEGAL_NOP_1
	3, // INSTRUCTION_MODE_ILLEGAL_NOP_2
	4, // INSTRUCTION_MODE_ILLEGAL_NOP_3
	8, // INSTRUCTION_MODE_ILLEGAL_NOP_4
	4, // INSTRUCTION_MODE_ILLEGAL_NOP_5
	};

#define INSTRUCTION_MODE_CYCLE(_TYPE_) \
	(((_TYPE_) > INSTRUCTION_MODE_MAX) ? INSTRUCTION_MODE_CYC[INSTRUCTION_MODE_IMPLIED] : \
		INSTRUCTION_MODE_CYC[_TYPE_])

static const uint8_t INSTRUCTION_MODE_LEN[] = {
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ABSOLUTE
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ABSOLUTE_INDEX_X
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ABSOLUTE_INDEX_Y
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ABSOLUTE_INDIRECT
	INSTRUCTION_LENGTH_NONE, // INSTRUCTION_MODE_ACCUMULATOR
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_IMMEDIATE
	INSTRUCTION_LENGTH_NONE, // INSTRUCTION_MODE_IMPLIED
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_INTERRUPT
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_RELATIVE
	INSTRUCTION_LENGTH_NONE, // INSTRUCTION_MODE_RETURN
	INSTRUCTION_LENGTH_NONE, // INSTRUCTION_MODE_STACK
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ZERO_PAGE
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ZERO_PAGE_INDEX_X
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ZERO_PAGE_INDIRECT
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ZERO_PAGE_RELATIVE
	// ---
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ILLEGAL_NOP_0
	INSTRUCTION_LENGTH_NONE, // INSTRUCTION_MODE_ILLEGAL_NOP_1
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ILLEGAL_NOP_2
	INSTRUCTION_LENGTH_BYTE, // INSTRUCTION_MODE_ILLEGAL_NOP_3
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ILLEGAL_NOP_4
	INSTRUCTION_LENGTH_WORD, // INSTRUCTION_MODE_ILLEGAL_NOP_5
	};

#define INSTRUCTION_MODE_LENGTH(_TYPE_) \
	(((_TYPE_) > INSTRUCTION_MODE_MAX) ? INSTRUCTION_MODE_LEN[INSTRUCTION_MODE_IMPLIED] : \
		INSTRUCTION_MODE_LEN[_TYPE_])

static const std::string INSTRUCTION_MODE_STR[] = {
	"a      ", // INSTRUCTION_MODE_ABSOLUTE
	"(a, x) ", // INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT
	"a, x   ", // INSTRUCTION_MODE_ABSOLUTE_INDEX_X
	"a, y   ", // INSTRUCTION_MODE_ABSOLUTE_INDEX_Y
	"(a)    ", // INSTRUCTION_MODE_ABSOLUTE_INDIRECT
	"A      ", // INSTRUCTION_MODE_ACCUMULATOR
	"#      ", // INSTRUCTION_MODE_IMMEDIATE
	"       ", // INSTRUCTION_MODE_IMPLIED
	"0      ", // INSTRUCTION_MODE_INTERRUPT
	"r      ", // INSTRUCTION_MODE_RELATIVE
	"       ", // INSTRUCTION_MODE_RETURN
	"       ", // INSTRUCTION_MODE_STACK
	"zp     ", // INSTRUCTION_MODE_ZERO_PAGE
	"(zp, x)", // INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT
	"zp, x  ", // INSTRUCTION_MODE_ZERO_PAGE_INDEX_X
	"zp, y  ", // INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y
	"(zp)   ", // INSTRUCTION_MODE_ZERO_PAGE_INDIRECT
	"(zp), y", // INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX
	"zp, r  ", // INSTRUCTION_MODE_ZERO_PAGE_RELATIVE
	// ---
	"(illeg)", // INSTRUCTION_MODE_ILLEGAL_NOP_0
	"(illeg)", // INSTRUCTION_MODE_ILLEGAL_NOP_1
	"(illeg)", // INSTRUCTION_MODE_ILLEGAL_NOP_2
	"(illeg)", // INSTRUCTION_MODE_ILLEGAL_NOP_3
	"(illeg)", // INSTRUCTION_MODE_ILLEGAL_NOP_4
	"(illeg)", // INSTRUCTION_MODE_ILLEGAL_NOP_5
	};

#define INSTRUCTION_MODE_STRING(_TYPE_) \
	(((_TYPE_) > INSTRUCTION_MODE_MAX) ? STRING_UNKNOWN : \
		STRING(INSTRUCTION_MODE_STR[_TYPE_]))

enum {
	// 0x00
	INSTRUCTION_TYPE_BRK_INTERRUPT = 0, // brk 0
	INSTRUCTION_TYPE_ORA_ZERO_PAGE_INDEX_INDIRECT, // ora (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_02, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_03, // nop
	INSTRUCTION_TYPE_TSB_ZERO_PAGE, // tsb zp
	INSTRUCTION_TYPE_ORA_ZERO_PAGE, // ora zp
	INSTRUCTION_TYPE_ASL_ZERO_PAGE, // asl zp
	INSTRUCTION_TYPE_RMB0_ZERO_PAGE, // rmb0 zp

	// 0x08
	INSTRUCTION_TYPE_PHP_STACK, // php
	INSTRUCTION_TYPE_ORA_IMMEDIATE, // ora #
	INSTRUCTION_TYPE_ASL_ACCUMULATOR, // asl A
	INSTRUCTION_TYPE_NOP_ILLEGAL_0B, // nop
	INSTRUCTION_TYPE_TSB_ABSOLUTE, // tsb a
	INSTRUCTION_TYPE_ORA_ABSOLUTE, // ora a
	INSTRUCTION_TYPE_ASL_ABSOLUTE, // asl a
	INSTRUCTION_TYPE_BBR0_ZERO_PAGE_RELATIVE, // bbr0 zp, r

	// 0x10
	INSTRUCTION_TYPE_BPL_RELATIVE, // bpl r
	INSTRUCTION_TYPE_ORA_ZERO_PAGE_INDIRECT_INDEX, // ora (zp), y
	INSTRUCTION_TYPE_ORA_ZERO_PAGE_INDIRECT, // ora (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_13, // nop
	INSTRUCTION_TYPE_TRB_ZERO_PAGE, // trb zp
	INSTRUCTION_TYPE_ORA_ZERO_PAGE_INDEX_X, // ora zp, x
	INSTRUCTION_TYPE_ASL_ZERO_PAGE_INDEX_X, // asl zp, x
	INSTRUCTION_TYPE_RMB1_ZERO_PAGE, // rmb1 zp

	// 0x18
	INSTRUCTION_TYPE_CLC_IMPLIED, // clc
	INSTRUCTION_TYPE_ORA_ABSOLUTE_INDEX_Y, // ora a, y
	INSTRUCTION_TYPE_INC_ACCUMULATOR, // inc A
	INSTRUCTION_TYPE_NOP_ILLEGAL_1B, // nop
	INSTRUCTION_TYPE_TRB_ABSOLUTE, // trb a
	INSTRUCTION_TYPE_ORA_ABSOLUTE_INDEX_X, // ora a, x
	INSTRUCTION_TYPE_ASL_ABSOLUTE_INDEX_X, // asl a, x
	INSTRUCTION_TYPE_BBR1_ZERO_PAGE_RELATIVE, // bbr1 zp, r

	// 0x20
	INSTRUCTION_TYPE_JSR_ABSOLUTE, // jsr a
	INSTRUCTION_TYPE_AND_ZERO_PAGE_INDEX_INDIRECT, // and (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_22, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_23, // nop
	INSTRUCTION_TYPE_BIT_ZERO_PAGE, // bit zp
	INSTRUCTION_TYPE_AND_ZERO_PAGE, // and zp
	INSTRUCTION_TYPE_ROL_ZERO_PAGE, // rol zp
	INSTRUCTION_TYPE_RMB2_ZERO_PAGE, // rmb2 zp

	// 0x28
	INSTRUCTION_TYPE_PLP_STACK, // plp
	INSTRUCTION_TYPE_AND_IMMEDIATE, // and #
	INSTRUCTION_TYPE_ROL_ACCUMULATOR, // rol A
	INSTRUCTION_TYPE_NOP_ILLEGAL_2B, // nop
	INSTRUCTION_TYPE_BIT_ABSOLUTE, // bit a
	INSTRUCTION_TYPE_AND_ABSOLUTE, // and a
	INSTRUCTION_TYPE_ROL_ABSOLUTE, // rol a
	INSTRUCTION_TYPE_BBR2_ZERO_PAGE_RELATIVE, // bbr2 zp, r

	// 0x30
	INSTRUCTION_TYPE_BMI_RELATIVE, // bmi r
	INSTRUCTION_TYPE_AND_ZERO_PAGE_INDIRECT_INDEX, // and (zp), y
	INSTRUCTION_TYPE_AND_ZERO_PAGE_INDIRECT, // and (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_33, // nop
	INSTRUCTION_TYPE_BIT_ZERO_PAGE_INDEX_X, // bit zp, x
	INSTRUCTION_TYPE_AND_ZERO_PAGE_INDEX_X, // and zp, x
	INSTRUCTION_TYPE_ROL_ZERO_PAGE_INDEX_X, // rol zp, x
	INSTRUCTION_TYPE_RMB3_ZERO_PAGE, // rmb3 zp

	// 0x38
	INSTRUCTION_TYPE_SEC_IMPLIED, // sec
	INSTRUCTION_TYPE_AND_ABSOLUTE_INDEX_Y, // and a, y
	INSTRUCTION_TYPE_DEC_ACCUMULATOR, // dec A
	INSTRUCTION_TYPE_NOP_ILLEGAL_3B, // nop
	INSTRUCTION_TYPE_BIT_ABSOLUTE_INDEX_X, // bit a, x
	INSTRUCTION_TYPE_AND_ABSOLUTE_INDEX_X, // and a, x
	INSTRUCTION_TYPE_ROL_ABSOLUTE_INDEX_X, // rol a, x
	INSTRUCTION_TYPE_BBR3_ZERO_PAGE_RELATIVE, // bbr3 zp, r

	// 0x40
	INSTRUCTION_TYPE_RTI_RETURN, // rti
	INSTRUCTION_TYPE_EOR_ZERO_PAGE_INDEX_INDIRECT, // eor (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_42, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_43, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_44, // nop
	INSTRUCTION_TYPE_EOR_ZERO_PAGE, // eor zp
	INSTRUCTION_TYPE_LSR_ZERO_PAGE, // lsr zp
	INSTRUCTION_TYPE_RMB4_ZERO_PAGE, // rmb4 zp

	// 0x48
	INSTRUCTION_TYPE_PHA_STACK, // pha
	INSTRUCTION_TYPE_EOR_IMMEDIATE, // eor #
	INSTRUCTION_TYPE_LSR_ACCUMULATOR, // lsr A
	INSTRUCTION_TYPE_NOP_ILLEGAL_4B, // nop
	INSTRUCTION_TYPE_JMP_ABSOLUTE, // jmp a
	INSTRUCTION_TYPE_EOR_ABSOLUTE, // eor a
	INSTRUCTION_TYPE_LSR_ABSOLUTE, // lsr a
	INSTRUCTION_TYPE_BBR4_ZERO_PAGE_RELATIVE, // bbr4 zp, r

	// 0x50
	INSTRUCTION_TYPE_BVC_RELATIVE, // bvc r
	INSTRUCTION_TYPE_EOR_ZERO_PAGE_INDIRECT_INDEX, // eor (zp), y
	INSTRUCTION_TYPE_EOR_ZERO_PAGE_INDIRECT, // eor (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_53, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_54, // nop
	INSTRUCTION_TYPE_EOR_ZERO_PAGE_INDEX_X, // eor zp, x
	INSTRUCTION_TYPE_LSR_ZERO_PAGE_INDEX_X, // lsr zp, x
	INSTRUCTION_TYPE_RMB5_ZERO_PAGE, // rmb5 zp

	// 0x58
	INSTRUCTION_TYPE_CLI_IMPLIED, // cli
	INSTRUCTION_TYPE_EOR_ABSOLUTE_INDEX_Y, // eor a, y
	INSTRUCTION_TYPE_PHY_STACK, // phy
	INSTRUCTION_TYPE_NOP_ILLEGAL_5B, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_5C, // nop
	INSTRUCTION_TYPE_EOR_ABSOLUTE_INDEX_X, // eor a, x
	INSTRUCTION_TYPE_LSR_ABSOLUTE_INDEX_X, // lsr a, x
	INSTRUCTION_TYPE_BBR5_ZERO_PAGE_RELATIVE, // bbr5 zp, r

	// 0x60
	INSTRUCTION_TYPE_RTS_RETURN, // rts
	INSTRUCTION_TYPE_ADC_ZERO_PAGE_INDEX_INDIRECT, // adc (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_62, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_63, // nop
	INSTRUCTION_TYPE_STZ_ZERO_PAGE, // stz zp
	INSTRUCTION_TYPE_ADC_ZERO_PAGE, // adc zp
	INSTRUCTION_TYPE_ROR_ZERO_PAGE, // ror zp
	INSTRUCTION_TYPE_RMB6_ZERO_PAGE, // rmb6 zp

	// 0x68
	INSTRUCTION_TYPE_PLA_STACK, // pla
	INSTRUCTION_TYPE_ADC_IMMEDIATE, // adc #
	INSTRUCTION_TYPE_ROR_ACCUMULATOR, // ror A
	INSTRUCTION_TYPE_NOP_ILLEGAL_6B, // nop
	INSTRUCTION_TYPE_JMP_ABSOLUTE_INDIRECT, // jmp (a)
	INSTRUCTION_TYPE_ADC_ABSOLUTE, // adc a
	INSTRUCTION_TYPE_ROR_ABSOLUTE, // ror a
	INSTRUCTION_TYPE_BBR6_ZERO_PAGE_RELATIVE, // bbr6 zp, r

	// 0x70
	INSTRUCTION_TYPE_BVS_RELATIVE, // bvs r
	INSTRUCTION_TYPE_ADC_ZERO_PAGE_INDIRECT_INDEX, // adc (zp), y
	INSTRUCTION_TYPE_ADC_ZERO_PAGE_INDIRECT, // adc (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_73, // nop
	INSTRUCTION_TYPE_STZ_ZERO_PAGE_INDEX_X, // stz zp, x
	INSTRUCTION_TYPE_ADC_ZERO_PAGE_INDEX_X, // adc zp, x
	INSTRUCTION_TYPE_ROR_ZERO_PAGE_INDEX_X, // ror zp, x
	INSTRUCTION_TYPE_RMB7_ZERO_PAGE, // rmb7 zp

	// 0x78
	INSTRUCTION_TYPE_SEI_IMPLIED, // sei
	INSTRUCTION_TYPE_ADC_ABSOLUTE_INDEX_Y, // adc a, y
	INSTRUCTION_TYPE_PLY_STACK, // ply
	INSTRUCTION_TYPE_NOP_ILLEGAL_7B, // nop
	INSTRUCTION_TYPE_JMP_ABSOLUTE_INDEX_INDIRECT, // jmp (a, x)
	INSTRUCTION_TYPE_ADC_ABSOLUTE_INDEX_X, // adc a, x
	INSTRUCTION_TYPE_ROR_ABSOLUTE_INDEX_X, // ror a, x
	INSTRUCTION_TYPE_BBR7_ZERO_PAGE_RELATIVE, // bbr7 zp, r

	// 0x80
	INSTRUCTION_TYPE_BRA_RELATIVE, // bra r
	INSTRUCTION_TYPE_STA_ZERO_PAGE_INDEX_INDIRECT, // sta (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_82, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_83, // nop
	INSTRUCTION_TYPE_STY_ZERO_PAGE, // sty zp
	INSTRUCTION_TYPE_STA_ZERO_PAGE, // sta zp
	INSTRUCTION_TYPE_STX_ZERO_PAGE, // stx zp
	INSTRUCTION_TYPE_SMB0_ZERO_PAGE, // smb0 zp

	// 0x88
	INSTRUCTION_TYPE_DEY_IMPLIED, // dey
	INSTRUCTION_TYPE_BIT_IMMEDIATE, // bit #
	INSTRUCTION_TYPE_TXA_IMPLIED, // txa
	INSTRUCTION_TYPE_NOP_ILLEGAL_8B, // nop
	INSTRUCTION_TYPE_STY_ABSOLUTE, // sty a
	INSTRUCTION_TYPE_STA_ABSOLUTE, // sta a
	INSTRUCTION_TYPE_STX_ABSOLUTE, // stx a
	INSTRUCTION_TYPE_BBS0_ZERO_PAGE_RELATIVE, // bbs0 zp, r

	// 0x90
	INSTRUCTION_TYPE_BCC_RELATIVE, // bcc r
	INSTRUCTION_TYPE_STA_ZERO_PAGE_INDIRECT_INDEX, // sta (zp), y
	INSTRUCTION_TYPE_STA_ZERO_PAGE_INDIRECT, // sta (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_93, // nop
	INSTRUCTION_TYPE_STY_ZERO_PAGE_INDEX_X, // sty zp, x
	INSTRUCTION_TYPE_STA_ZERO_PAGE_INDEX_X, // sta zp, x
	INSTRUCTION_TYPE_STX_ZERO_PAGE_INDEX_Y, // stx zp, y
	INSTRUCTION_TYPE_SMB1_ZERO_PAGE, // smb1 zp

	// 0x98
	INSTRUCTION_TYPE_TYA_IMPLIED, // tya
	INSTRUCTION_TYPE_STA_ABSOLUTE_INDEX_Y, // sta a, y
	INSTRUCTION_TYPE_TXS_IMPLIED, // txs
	INSTRUCTION_TYPE_NOP_ILLEGAL_9B, // nop
	INSTRUCTION_TYPE_STZ_ABSOLUTE, // stz a
	INSTRUCTION_TYPE_STA_ABSOLUTE_INDEX_X, // sta a, x
	INSTRUCTION_TYPE_STZ_ABSOLUTE_INDEX_X, // stz a, x
	INSTRUCTION_TYPE_BBS1_ZERO_PAGE_RELATIVE, // bbs1 zp, r

	// 0xa0
	INSTRUCTION_TYPE_LDY_IMMEDIATE, // ldy #
	INSTRUCTION_TYPE_LDA_ZERO_PAGE_INDEX_INDIRECT, // lda (zp, x)
	INSTRUCTION_TYPE_LDX_IMMEDIATE, // ldx #
	INSTRUCTION_TYPE_NOP_ILLEGAL_A3, // nop
	INSTRUCTION_TYPE_LDY_ZERO_PAGE, // ldy zp
	INSTRUCTION_TYPE_LDA_ZERO_PAGE, // lda zp
	INSTRUCTION_TYPE_LDX_ZERO_PAGE, // ldx zp
	INSTRUCTION_TYPE_SMB2_ZERO_PAGE, // smb2 zp

	// 0xa8
	INSTRUCTION_TYPE_TAY_IMPLIED, // tay
	INSTRUCTION_TYPE_LDA_IMMEDIATE, // lda #
	INSTRUCTION_TYPE_TAX_IMPLIED, // tax
	INSTRUCTION_TYPE_NOP_ILLEGAL_AB, // nop
	INSTRUCTION_TYPE_LDY_ACCUMULATOR, // ldy A
	INSTRUCTION_TYPE_LDA_ABSOLUTE, // lda a
	INSTRUCTION_TYPE_LDX_ABSOLUTE, // ldx a
	INSTRUCTION_TYPE_BBS2_ZERO_PAGE_RELATIVE, // bbs2 zp, r

	// 0xb0
	INSTRUCTION_TYPE_BCS_RELATIVE, // bcs r
	INSTRUCTION_TYPE_LDA_ZERO_PAGE_INDIRECT_INDEX, // lda (zp), y
	INSTRUCTION_TYPE_LDA_ZERO_PAGE_INDIRECT, // lda (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_B3, // nop
	INSTRUCTION_TYPE_LDY_ZERO_PAGE_INDEX_X, // ldy zp, x
	INSTRUCTION_TYPE_LDA_ZERO_PAGE_INDEX_X, // lda zp, x
	INSTRUCTION_TYPE_LDX_ZERO_PAGE_INDEX_Y, // ldx zp, y
	INSTRUCTION_TYPE_SMB3_ZERO_PAGE, // smb3 zp

	// 0xb8
	INSTRUCTION_TYPE_CLV_IMPLIED, // clv
	INSTRUCTION_TYPE_LDA_ABSOLUTE_INDEX_Y, // lda a, y
	INSTRUCTION_TYPE_TSX_IMPLIED, // tsx
	INSTRUCTION_TYPE_NOP_ILLEGAL_BB, // nop
	INSTRUCTION_TYPE_LDY_ABSOLUTE_INDEX_X, // ldy a, x
	INSTRUCTION_TYPE_LDA_ABSOLUTE_INDEX_X, // lda a, x
	INSTRUCTION_TYPE_LDX_ABSOLUTE_INDEX_Y, // ldx a, y
	INSTRUCTION_TYPE_BBS3_ZERO_PAGE_RELATIVE, // bbs3 zp, r

	// 0xc0
	INSTRUCTION_TYPE_CPY_IMMEDIATE, // cpy #
	INSTRUCTION_TYPE_CMP_ZERO_PAGE_INDEX_INDIRECT, // cmp (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_C2, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_C3, // nop
	INSTRUCTION_TYPE_CPY_ZERO_PAGE, // cpy zp
	INSTRUCTION_TYPE_CMP_ZERO_PAGE, // cmp zp
	INSTRUCTION_TYPE_DEC_ZERO_PAGE, // dec zp
	INSTRUCTION_TYPE_SMB4_ZERO_PAGE, // smb4 zp

	// 0xc8
	INSTRUCTION_TYPE_INY_IMPLIED, // iny
	INSTRUCTION_TYPE_CMP_IMMEDIATE, // cmp #
	INSTRUCTION_TYPE_DEX_IMPLIED, // dex
	INSTRUCTION_TYPE_WAI_IMPLIED, // wai
	INSTRUCTION_TYPE_CPY_ABSOLUTE, // cpy a
	INSTRUCTION_TYPE_CMP_ABSOLUTE, // cmp a
	INSTRUCTION_TYPE_DEC_ABSOLUTE, // dec a
	INSTRUCTION_TYPE_BBS4_ZERO_PAGE_RELATIVE, // bbs4 zp, r

	// 0xd0
	INSTRUCTION_TYPE_BNE_RELATIVE, // bne r
	INSTRUCTION_TYPE_CMP_ZERO_PAGE_INDIRECT_INDEX, // cmp (zp), y
	INSTRUCTION_TYPE_CMP_ZERO_PAGE_INDIRECT, // cmp (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_D3, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_D4, // nop
	INSTRUCTION_TYPE_CMP_ZERO_PAGE_INDEX_X, // cmp zp, x
	INSTRUCTION_TYPE_DEC_ZERO_PAGE_INDEX_X, // dec zp, x
	INSTRUCTION_TYPE_SMB5_ZERO_PAGE, // smb5 zp

	// 0xd8
	INSTRUCTION_TYPE_CLD_IMPLIED, // cld
	INSTRUCTION_TYPE_CMP_ABSOLUTE_INDEX_Y, // cmp a, y
	INSTRUCTION_TYPE_PHX_STACK, // phx
	INSTRUCTION_TYPE_STP_IMPLIED, // stp
	INSTRUCTION_TYPE_NOP_ILLEGAL_DC, // nop
	INSTRUCTION_TYPE_CMP_ABSOLUTE_INDEX_X, // cmp a, x
	INSTRUCTION_TYPE_DEC_ABSOLUTE_INDEX_X, // dec a, x
	INSTRUCTION_TYPE_BBS5_ZERO_PAGE_RELATIVE, // bbs5 zp, r

	// 0xe0
	INSTRUCTION_TYPE_CPX_IMMEDIATE, // cpx #
	INSTRUCTION_TYPE_SBC_ZERO_PAGE_INDEX_INDIRECT, // sbc (zp, x)
	INSTRUCTION_TYPE_NOP_ILLEGAL_E2, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_E3, // nop
	INSTRUCTION_TYPE_CPX_ZERO_PAGE, // cpx zp
	INSTRUCTION_TYPE_SBC_ZERO_PAGE, // sbc zp
	INSTRUCTION_TYPE_INC_ZERO_PAGE, // inc zp
	INSTRUCTION_TYPE_SMB6_ZERO_PAGE, // smb6 zp

	// 0xe8
	INSTRUCTION_TYPE_INX_IMPLIED, // inx
	INSTRUCTION_TYPE_SBC_IMMEDIATE, // sbc #
	INSTRUCTION_TYPE_NOP_IMPLIED, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_EB, // nop
	INSTRUCTION_TYPE_CPX_ABSOLUTE, // cpx a
	INSTRUCTION_TYPE_SBC_ABSOLUTE, // sbc a
	INSTRUCTION_TYPE_INC_ABSOLUTE, // inc a
	INSTRUCTION_TYPE_BBS6_ZERO_PAGE_RELATIVE, // bbs6 zp, r

	// 0xf0
	INSTRUCTION_TYPE_BEQ_RELATIVE, // beq r
	INSTRUCTION_TYPE_SBC_ZERO_PAGE_INDIRECT_INDEX, // sbc (zp), y
	INSTRUCTION_TYPE_SBC_ZERO_PAGE_INDIRECT, // sbc (zp)
	INSTRUCTION_TYPE_NOP_ILLEGAL_F3, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_F4, // nop
	INSTRUCTION_TYPE_SBC_ZERO_PAGE_INDEX_X, // sbc zp, x
	INSTRUCTION_TYPE_INC_ZERO_PAGE_INDEX_X, // inc zp, x
	INSTRUCTION_TYPE_SMB7_ZERO_PAGE, // smb7 zp

	// 0xf8
	INSTRUCTION_TYPE_SED_IMPLIED, // sed
	INSTRUCTION_TYPE_SBC_ABSOLUTE_INDEX_Y, // sbc a, y
	INSTRUCTION_TYPE_PLX_STACK, // plx
	INSTRUCTION_TYPE_NOP_ILLEGAL_FB, // nop
	INSTRUCTION_TYPE_NOP_ILLEGAL_FC, // nop
	INSTRUCTION_TYPE_SBC_ABSOLUTE_INDEX_X, // sbc a, x
	INSTRUCTION_TYPE_INC_ABSOLUTE_INDEX_X, // inc a, x
	INSTRUCTION_TYPE_BBS7_ZERO_PAGE_RELATIVE, // bbs7 zp, r
};

typedef struct {
	int type;
	int mode;
	uint8_t length;
	uint8_t cycle;
} instruction_t;

static const instruction_t CMD[] = {

	// 0x00
	{ INSTRUCTION_BRK, INSTRUCTION_MODE_INTERRUPT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_INTERRUPT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_INTERRUPT) }, // brk 0
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // ora (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_TSB, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // tsb zp
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // ora zp
	{ INSTRUCTION_ASL, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // asl zp
	{ INSTRUCTION_RMB0, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb0 zp

	// 0x08
	{ INSTRUCTION_PHP, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // php
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // ora #
	{ INSTRUCTION_ASL, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // asl A
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_TSB, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // tsb a
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // ora a
	{ INSTRUCTION_ASL, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // asl a
	{ INSTRUCTION_BBR0, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr0 zp, r

	// 0x10
	{ INSTRUCTION_BPL, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bpl r
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // ora (zp), y
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // ora (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_TRB, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // trb zp
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // ora zp, x
	{ INSTRUCTION_ASL, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // asl zp, x
	{ INSTRUCTION_RMB1, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb1 zp

	// 0x18
	{ INSTRUCTION_CLC, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // clc
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // ora a, y
	{ INSTRUCTION_INC, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // inc A
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_TRB, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // trb a
	{ INSTRUCTION_ORA, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // ora a, x
	{ INSTRUCTION_ASL, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // asl a, x
	{ INSTRUCTION_BBR1, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr1 zp, r

	// 0x20
	{ INSTRUCTION_JSR, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // jsr a
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // and (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_BIT, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // bit zp
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // and zp
	{ INSTRUCTION_ROL, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rol zp
	{ INSTRUCTION_RMB2, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb2 zp

	// 0x28
	{ INSTRUCTION_PLP, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // plp
	{ INSTRUCTION_AND, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // and #
	{ INSTRUCTION_ROL, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // rol A
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_BIT, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // bit a
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // and a
	{ INSTRUCTION_ROL, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // rol a
	{ INSTRUCTION_BBR2, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr2 zp, r

	// 0x30
	{ INSTRUCTION_BMI, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bmi r
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // and (zp), y
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // and (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_BIT, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // bit zp, x
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // and zp, x
	{ INSTRUCTION_ROL, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // rol zp, x
	{ INSTRUCTION_RMB3, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb3 zp

	// 0x38
	{ INSTRUCTION_SEC, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // sec
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // and a, y
	{ INSTRUCTION_DEC, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // dec A
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_BIT, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // bit a, x
	{ INSTRUCTION_AND, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // and a, x
	{ INSTRUCTION_ROL, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // rol a, x
	{ INSTRUCTION_BBR3, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr3 zp, r

	// 0x40
	{ INSTRUCTION_RTI, INSTRUCTION_MODE_RETURN, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RETURN), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RETURN) }, // rti
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // eor (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_2, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_2), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_2) }, // nop
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // eor zp
	{ INSTRUCTION_LSR, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // lsr zp
	{ INSTRUCTION_RMB4, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb4 zp

	// 0x48
	{ INSTRUCTION_PHA, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // pha
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // eor #
	{ INSTRUCTION_LSR, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // lsr A
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_JMP, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // jmp a
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // eor a
	{ INSTRUCTION_LSR, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // lsr a
	{ INSTRUCTION_BBR4, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr4 zp, r

	// 0x50
	{ INSTRUCTION_BVC, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bvc r
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // eor (zp), y
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // eor (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_3, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_3), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_3) }, // nop
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // eor zp, x
	{ INSTRUCTION_LSR, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // lsr zp, x
	{ INSTRUCTION_RMB5, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb5 zp

	// 0x58
	{ INSTRUCTION_CLI, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // cli
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // eor a, y
	{ INSTRUCTION_PHY, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // phy
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_4, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_4), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_4) }, // nop
	{ INSTRUCTION_EOR, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // eor a, x
	{ INSTRUCTION_LSR, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // lsr a, x
	{ INSTRUCTION_BBR5, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr5 zp, r

	// 0x60
	{ INSTRUCTION_RTS, INSTRUCTION_MODE_RETURN, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RETURN), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RETURN) }, // rts
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // adc (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_STZ, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // stz zp
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // adc zp
	{ INSTRUCTION_ROR, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // ror zp
	{ INSTRUCTION_RMB6, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb6 zp

	// 0x68
	{ INSTRUCTION_PLA, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // pla
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // adc #
	{ INSTRUCTION_ROR, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // ror A
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_JMP, INSTRUCTION_MODE_ABSOLUTE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDIRECT) }, // jmp (a)
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // adc a
	{ INSTRUCTION_ROR, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // ror a
	{ INSTRUCTION_BBR6, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr6 zp, r

	// 0x70
	{ INSTRUCTION_BVS, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bvs r
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // adc (zp), y
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // adc (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_STZ, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // stz zp, x
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // adc zp, x
	{ INSTRUCTION_ROR, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // ror zp, x
	{ INSTRUCTION_RMB7, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // rmb7 zp

	// 0x78
	{ INSTRUCTION_SEI, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // sei
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // adc a, y
	{ INSTRUCTION_PLY, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // ply
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_JMP, INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_INDIRECT) }, // jmp (a, x)
	{ INSTRUCTION_ADC, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // adc a, x
	{ INSTRUCTION_ROR, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // ror a, x
	{ INSTRUCTION_BBR7, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbr7 zp, r

	// 0x80
	{ INSTRUCTION_BRA, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bra r
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // sta (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_STY, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // sty zp
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // sta zp
	{ INSTRUCTION_STX, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // stx zp
	{ INSTRUCTION_SMB0, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb0 zp

	// 0x88
	{ INSTRUCTION_DEY, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // dey
	{ INSTRUCTION_BIT, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // bit #
	{ INSTRUCTION_TXA, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // txa
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_STY, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // sty a
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // sta a
	{ INSTRUCTION_STX, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // stx a
	{ INSTRUCTION_BBS0, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs0 zp, r

	// 0x90
	{ INSTRUCTION_BCC, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bcc r
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // sta (zp), y
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // sta (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_STY, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // sty zp, x
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // sta zp, x
	{ INSTRUCTION_STX, INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y) }, // stx zp, y
	{ INSTRUCTION_SMB1, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb1 zp

	// 0x98
	{ INSTRUCTION_TYA, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // tya
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // sta a, y
	{ INSTRUCTION_TXS, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // txs
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_STZ, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // stz a
	{ INSTRUCTION_STA, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // sta a, x
	{ INSTRUCTION_STZ, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // stz a, x
	{ INSTRUCTION_BBS1, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs1 zp, r

	// 0xa0
	{ INSTRUCTION_LDY, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // ldy #
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // lda (zp, x)
	{ INSTRUCTION_LDX, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // ldx #
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_LDY, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // ldy zp
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // lda zp
	{ INSTRUCTION_LDX, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // ldx zp
	{ INSTRUCTION_SMB2, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb2 zp

	// 0xa8
	{ INSTRUCTION_TAY, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // tay
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // lda #
	{ INSTRUCTION_TAX, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // tax
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_LDY, INSTRUCTION_MODE_ACCUMULATOR, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ACCUMULATOR), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ACCUMULATOR) }, // ldy A
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // lda a
	{ INSTRUCTION_LDX, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // ldx a
	{ INSTRUCTION_BBS2, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs2 zp, r

	// 0xb0
	{ INSTRUCTION_BCS, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bcs r
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // lda (zp), y
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // lda (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_LDY, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // ldy zp, x
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // lda zp, x
	{ INSTRUCTION_LDX, INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_Y) }, // ldx zp, y
	{ INSTRUCTION_SMB3, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb3 zp

	// 0xb8
	{ INSTRUCTION_CLV, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // clv
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // lda a, y
	{ INSTRUCTION_TSX, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // tsx
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_LDY, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // ldy a, x
	{ INSTRUCTION_LDA, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // lda a, x
	{ INSTRUCTION_LDX, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // ldx a, y
	{ INSTRUCTION_BBS3, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs3 zp, r

	// 0xc0
	{ INSTRUCTION_CPY, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // cpy #
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // cmp (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_CPY, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // cpy zp
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // cmp zp
	{ INSTRUCTION_DEC, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // dec zp
	{ INSTRUCTION_SMB4, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb4 zp

	// 0xc8
	{ INSTRUCTION_INY, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // iny
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // cmp #
	{ INSTRUCTION_DEX, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // dex
	{ INSTRUCTION_WAI, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // wai
	{ INSTRUCTION_CPY, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // cpy a
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // cmp a
	{ INSTRUCTION_DEC, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // dec a
	{ INSTRUCTION_BBS4, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs4 zp, r

	// 0xd0
	{ INSTRUCTION_BNE, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // bne r
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // cmp (zp), y
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // cmp (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_3, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_3), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_3) }, // nop
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // cmp zp, x
	{ INSTRUCTION_DEC, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // dec zp, x
	{ INSTRUCTION_SMB5, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb5 zp

	// 0xd8
	{ INSTRUCTION_CLD, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // cld
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // cmp a, y
	{ INSTRUCTION_PHX, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // phx
	{ INSTRUCTION_STP, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // stp
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_5, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_5), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_5) }, // nop
	{ INSTRUCTION_CMP, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // cmp a, x
	{ INSTRUCTION_DEC, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // dec a, x
	{ INSTRUCTION_BBS5, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs5 zp, r

	// 0xe0
	{ INSTRUCTION_CPX, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // cpx #
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_INDIRECT) }, // sbc (zp, x)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_0, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_0), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_0) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_CPX, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // cpx zp
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // sbc zp
	{ INSTRUCTION_INC, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // inc zp
	{ INSTRUCTION_SMB6, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb6 zp

	// 0xe8
	{ INSTRUCTION_INX, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // inx
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_IMMEDIATE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMMEDIATE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMMEDIATE) }, // sbc #
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_CPX, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // cpx a
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // sbc a
	{ INSTRUCTION_INC, INSTRUCTION_MODE_ABSOLUTE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE) }, // inc a
	{ INSTRUCTION_BBS6, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs6 zp, r

	// 0xf0
	{ INSTRUCTION_BEQ, INSTRUCTION_MODE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_RELATIVE) }, // beq r
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT_INDEX) }, // sbc (zp), y
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ZERO_PAGE_INDIRECT, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDIRECT) }, // sbc (zp)
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_3, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_3), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_3) }, // nop
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // sbc zp, x
	{ INSTRUCTION_INC, INSTRUCTION_MODE_ZERO_PAGE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_INDEX_X) }, // inc zp, x
	{ INSTRUCTION_SMB7, INSTRUCTION_MODE_ZERO_PAGE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE) }, // smb7 zp

	// 0xf8
	{ INSTRUCTION_SED, INSTRUCTION_MODE_IMPLIED, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_IMPLIED), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_IMPLIED) }, // sed
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ABSOLUTE_INDEX_Y, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_Y) }, // sbc a, y
	{ INSTRUCTION_PLX, INSTRUCTION_MODE_STACK, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_STACK), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_STACK) }, // plx
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_1, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_1), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_1) }, // nop
	{ INSTRUCTION_NOP, INSTRUCTION_MODE_ILLEGAL_NOP_5, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ILLEGAL_NOP_5), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ILLEGAL_NOP_5) }, // nop
	{ INSTRUCTION_SBC, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // sbc a, x
	{ INSTRUCTION_INC, INSTRUCTION_MODE_ABSOLUTE_INDEX_X, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ABSOLUTE_INDEX_X), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ABSOLUTE_INDEX_X) }, // inc a, x
	{ INSTRUCTION_BBS7, INSTRUCTION_MODE_ZERO_PAGE_RELATIVE, INSTRUCTION_MODE_LENGTH(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE), INSTRUCTION_MODE_CYCLE(INSTRUCTION_MODE_ZERO_PAGE_RELATIVE) }, // bbs7 zp, r
	};

#define INSTRUCTION(_TYPE_) \
	(((_TYPE_) > UINT8_MAX) ? CMD[INSTRUCTION_TYPE_NOP_IMPLIED] : \
		CMD[_TYPE_])

#endif // C65_COMMON_INSTRUCTION_H_
